import {test,expect} from '@playwright/test';

async function login(page,persona){return page.evaluate(async persona=>{const r=await fetch('/api/auth/demo-login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({persona})});return{status:r.status,body:await r.json()}},persona)}
async function request(page,method,path,csrf,body){return page.evaluate(async({method,path,csrf,body})=>{const r=await fetch(path,{method,headers:{'content-type':'application/json','x-csrf-token':csrf},body:body===undefined?undefined:JSON.stringify(body)});let json={};try{json=await r.json()}catch{}return{status:r.status,body:json}},{method,path,csrf,body})}

test('Art Week Programme groups reviewed calendar records and turns PLANNED into My Day',async({page})=>{
 await page.goto('/',{waitUntil:'domcontentloaded'});let auth=await login(page,'OPERATOR');expect(auth.status).toBe(200);const csrf=auth.body.csrf,token=Date.now().toString(),base=Date.now()+7*864e5;
 const event=await request(page,'POST','/api/calendar/events',csrf,{slug:'browser-programme-event-'+token,title:{en:'Programme Browser Event '+token,ru:'Браузерное событие программы '+token},summary:{en:'Reviewed programme entry',ru:'Проверенный пункт программы'},eventType:'ARTIST_TALK',venueMode:'PHYSICAL',venueName:{en:'Programme Test Gallery',ru:'Тестовая галерея программы'},city:{en:'Amsterdam',ru:'Амстердам'},country:{en:'Netherlands',ru:'Нидерланды'},timezone:'Europe/Amsterdam',startsAt:new Date(base).toISOString(),endsAt:new Date(base+90*60000).toISOString(),visibility:'PUBLIC'});expect(event.status).toBe(201);const eventId=event.body.event.id;expect((await request(page,'POST','/api/calendar/events/'+eventId+'/submit',csrf,{})).status).toBe(200);expect((await request(page,'POST','/api/calendar/review/events/'+eventId,csrf,{decision:'APPROVE'})).status).toBe(200);
 const made=await request(page,'POST','/api/programmes',csrf,{slug:'browser-art-week-'+token,programmeType:'ART_WEEK',title:{en:'Browser Art Week '+token,ru:'Браузерная арт-неделя '+token},summary:{en:'Reviewed multi-day programme',ru:'Проверенная многодневная программа'},city:{en:'Amsterdam',ru:'Амстердам'},country:{en:'Netherlands',ru:'Нидерланды'},timezone:'Europe/Amsterdam',startsAt:new Date(base-864e5).toISOString(),endsAt:new Date(base+3*864e5).toISOString(),visibility:'PUBLIC'});expect(made.status).toBe(201);const programmeId=made.body.programme.id,slug=made.body.programme.slug;
 expect((await request(page,'PUT','/api/programmes/'+programmeId+'/entries',csrf,{entityType:'EVENT',entityId:eventId,neighbourhood:{en:'Jordaan',ru:'Йордан'},dayLabel:{en:'Day 1',ru:'День 1'},featured:true,sortOrder:10})).status).toBe(200);
 expect((await request(page,'POST','/api/programmes/'+programmeId+'/submit',csrf,{})).status).toBe(200);expect((await request(page,'POST','/api/programmes/review/'+programmeId,csrf,{decision:'APPROVE'})).status).toBe(200);

 auth=await login(page,'BUYER');expect(auth.status).toBe(200);const buyerCsrf=auth.body.csrf;expect((await request(page,'POST','/api/calendar/participation',buyerCsrf,{entityType:'EVENT',entityId:eventId,state:'PLANNED'})).status).toBe(200);expect((await request(page,'PUT','/api/programmes/'+programmeId+'/day-plan',buyerCsrf,{entityType:'EVENT',entityId:eventId,sortOrder:10,privateNote:'First stop'})).status).toBe(200);
 await page.goto('/#programme/'+slug,{waitUntil:'domcontentloaded'});
 const programme=page.locator('.programme-page');await expect(programme).toBeVisible();await expect(programme).toContainText(token);await expect(programme).toContainText(/Jordaan|Йордан/);await expect(programme.locator('.programme-my-day')).toContainText(/Programme Browser Event|Браузерное событие программы/);await expect(programme.locator('[data-programme-plan].active')).toBeVisible();await expect(programme.locator('[data-programme-day]')).toHaveCount(1);
 const officialIcs=await page.evaluate(async id=>{const r=await fetch('/api/programmes/'+id+'/ics');return{status:r.status,type:r.headers.get('content-type'),body:await r.text()}},programmeId);expect(officialIcs.status).toBe(200);expect(officialIcs.type).toMatch(/text\/calendar/);expect(officialIcs.body).toContain('BEGIN:VEVENT');
 const mineIcs=await page.evaluate(async id=>{const r=await fetch('/api/programmes/'+id+'/mine.ics');return{status:r.status,type:r.headers.get('content-type'),body:await r.text()}},programmeId);expect(mineIcs.status).toBe(200);expect(mineIcs.type).toMatch(/text\/calendar/);expect(mineIcs.body).toContain('First stop');
});

test('Art Calendar links into reviewed programme catalogue',async({page})=>{
 await page.goto('/#events',{waitUntil:'domcontentloaded'});const calendar=page.locator('.cultural-calendar-page');await expect(calendar).toBeVisible();const link=calendar.locator('.calendar-programmes-callout a[href="#programmes"]');await expect(link).toBeVisible();await link.click();await expect(page.locator('.programme-index-page')).toBeVisible();await expect(page.locator('.programme-index-page')).toContainText(/арт-недели|Art weeks/i);
});
