export const SALE='sale-collector-2026-09';
export const BUYER_ID='preview-buyer';
export const SELLER_ID='preview-seller';
export const bi=(en,ru)=>({en,ru});
export const nowIso=()=>new Date().toISOString();
export const sellers=new Map([
['dealer-vermeer',{id:'dealer-vermeer',name:'Maison Vermeer Antiques',city:bi('Amsterdam','Амстердам'),country:bi('Netherlands','Нидерланды'),since:1987,verified:true,about:bi('European furniture, decorative arts and objects with a focus on documented condition and provenance.','Европейская мебель, декоративное искусство и предметы с акцентом на документированное состояние и провенанс.'),responseTime:bi('Usually replies within 4 hours','Обычно отвечает в течение 4 часов')}],
['dealer-north',{id:'dealer-north',name:'North & Co. Antiques',city:bi('London','Лондон'),country:bi('United Kingdom','Великобритания'),since:1994,verified:true,about:bi('Objects, sculpture and works on paper sourced from European private collections.','Предметы искусства, скульптура и графика из европейских частных коллекций.'),responseTime:bi('Usually replies within 1 business day','Обычно отвечает в течение 1 рабочего дня')}],
['seller-preview',{id:'seller-preview',name:'Preview Dealer Cabinet',city:bi('Amsterdam','Амстердам'),country:bi('Netherlands','Нидерланды'),since:2026,verified:true,about:bi('Demonstration seller account for testing the ANTIQUA dealer workflow.','Демонстрационный кабинет продавца для проверки рабочего процесса ANTIQUA.'),responseTime:bi('Preview account','Демонстрационный аккаунт')}]
]);
const rows=[
['101','European Decorative Arts','Европейское декоративное искусство','French, Louis XVI period','Франция, период Людовика XVI','A gilt-bronze mounted mantel clock','Каминные часы с золочёной бронзой','late 18th century','конец XVIII века','France','Франция',18000,26000,'https://images.metmuseum.org/CRDImages/es/web-large/DP340468.jpg'],
['102','European Ceramics','Европейская керамика','Delft workshop','Делфтская мастерская','A blue-and-white charger','Большое сине-белое блюдо','18th century','XVIII век','Netherlands','Нидерланды',2800,4200,'https://images.metmuseum.org/CRDImages/es/web-large/DP254624.jpg'],
['103','Sculpture','Скульптура','European School','Европейская школа','Study of a horse','Этюд лошади','late 19th century','конец XIX века','Europe','Европа',6000,9000,'https://images.metmuseum.org/CRDImages/es/web-large/DP169405.jpg'],
['104','European Paintings','Европейская живопись','European School','Европейская школа','River landscape at dusk','Речной пейзаж в сумерках','19th century','XIX век','Europe','Европа',9000,14000,'https://images.metmuseum.org/CRDImages/ep/web-large/DP145903.jpg'],
['105','Works of Art','Предметы искусства','Italian','Италия','A carved marble fragment','Резной мраморный фрагмент','18th–19th century','XVIII–XIX век','Italy','Италия',7500,11000,'https://images.metmuseum.org/CRDImages/es/web-large/DP151938.jpg'],
['106','European Furniture','Европейская мебель','French','Франция','A neoclassical occasional table','Неоклассический приставной столик','circa 1800','около 1800 года','France','Франция',12000,18000,'https://images.metmuseum.org/CRDImages/es/web-large/DP247929.jpg'],
['107','Asian Works of Art','Азиатское искусство','Chinese','Китай','A monochrome glazed vessel','Сосуд с монохромной глазурью','Qing dynasty style','в стиле династии Цин','China','Китай',5000,8000,'https://images.metmuseum.org/CRDImages/as/web-large/DP251139.jpg'],
['108','Books & Manuscripts','Книги и рукописи','Continental European','Континентальная Европа','An illuminated manuscript leaf','Лист иллюминированной рукописи','15th century style','в стиле XV века','Europe','Европа',3500,5500,'https://images.metmuseum.org/CRDImages/md/web-large/DP-16286-001.jpg'],
['109','European Furniture','Европейская мебель','Northern Italian','Северная Италия','A walnut commode','Ореховый комод','circa 1780','около 1780 года','Italy','Италия',6800,9000,'https://images.metmuseum.org/CRDImages/es/web-large/DP247929.jpg'],
['110','Silver','Серебро','English','Англия','A pair of silver candlesticks','Пара серебряных подсвечников','early 19th century','начало XIX века','United Kingdom','Великобритания',4200,6200,'https://images.metmuseum.org/CRDImages/es/web-large/DP340468.jpg'],
['111','European Ceramics','Европейская керамика','Meissen style','в стиле Мейсена','A porcelain figure group','Фарфоровая скульптурная группа','19th century','XIX век','Germany','Германия',3200,4800,'https://images.metmuseum.org/CRDImages/es/web-large/DP254624.jpg'],
['112','Sculpture','Скульптура','French School','Французская школа','A bronze portrait bust','Бронзовый портретный бюст','circa 1900','около 1900 года','France','Франция',8500,12000,'https://images.metmuseum.org/CRDImages/es/web-large/DP169405.jpg']
];
export const lots=rows.map(x=>({id:`lot-${x[0]}`,lotNumber:Number(x[0]),department:bi(x[1],x[2]),maker:bi(x[3],x[4]),title:bi(x[5],x[6]),period:bi(x[7],x[8]),origin:bi(x[9],x[10]),currency:'EUR',estimateLow:x[11],estimateHigh:x[12],image:x[13],cataloguing:bi('Demonstration catalogue record. A real publication requires dimensions, marks, materials and specialist review.','Демонстрационная каталожная запись. Для реальной публикации обязательны размеры, маркировки, материалы и проверка специалистом.'),provenance:bi(['Demonstration provenance — not externally verified'],['Демонстрационный провенанс — внешне не подтверждён']),condition:bi('Illustrative condition report only; damage and restoration must be documented photographically.','Иллюстративный отчёт о состоянии; повреждения и реставрации должны быть зафиксированы фотографиями.'),literature:bi([],[])}));
export const step=n=>n<1000?50:n<5000?100:n<10000?250:n<20000?500:n<50000?1000:2500;
const t0=Date.now();
const auctionSeed=[[101,14500,9,5,16500],[102,2600,4,7,3200],[103,5250,7,9,6500],[104,7200,3,11,8500],[105,6000,5,14,7500],[106,10000,2,17,13000]];
export const auctions=auctionSeed.map(([n,cur,count,h,res])=>({id:`auc-${n}`,saleId:SALE,lotId:`lot-${n}`,currency:'EUR',baselineBid:cur,currentBid:cur,increment:step(cur),bidCount:count,reservePrice:res,reserveMet:cur>=res,startsAt:new Date(t0-7200000).toISOString(),endsAt:new Date(t0+h*3600000).toISOString(),state:'LIVE',leaderClientId:null,proxyBids:[],history:[{amount:cur,bidder:'Bidder •••',time:new Date(t0-1200000).toISOString(),type:'seed'}]}));
export const listings=new Map([
['lst-107',{id:'lst-107',lotId:'lot-107',sellerId:'dealer-vermeer',saleType:'BUY_NOW',price:7200,currency:'EUR',negotiable:true,status:'ACTIVE',shippingFrom:'Amsterdam',createdAt:nowIso()}],
['lst-108',{id:'lst-108',lotId:'lot-108',sellerId:'dealer-north',saleType:'MAKE_OFFER',price:5200,currency:'EUR',negotiable:true,status:'ACTIVE',shippingFrom:'London',createdAt:nowIso()}],
['lst-109',{id:'lst-109',lotId:'lot-109',sellerId:'seller-preview',saleType:'BUY_NOW',price:7800,currency:'EUR',negotiable:true,status:'ACTIVE',shippingFrom:'Amsterdam',createdAt:nowIso()}],
['lst-110',{id:'lst-110',lotId:'lot-110',sellerId:'seller-preview',saleType:'MAKE_OFFER',price:5600,currency:'EUR',negotiable:true,status:'ACTIVE',shippingFrom:'Amsterdam',createdAt:nowIso()}],
['lst-111',{id:'lst-111',lotId:'lot-111',sellerId:'dealer-vermeer',saleType:'BUY_NOW',price:4300,currency:'EUR',negotiable:false,status:'ACTIVE',shippingFrom:'Amsterdam',createdAt:nowIso()}],
['lst-112',{id:'lst-112',lotId:'lot-112',sellerId:'dealer-north',saleType:'BUY_NOW',price:10500,currency:'EUR',negotiable:true,status:'ACTIVE',shippingFrom:'London',createdAt:nowIso()}]
]);
