export const bi=(en,ru)=>({en,ru});
export const SALE='sale-collector-2026-09';
export const BUYER_ID='preview-buyer';
export const SELLER_ID='preview-seller';

export const sellers=new Map([
 ['dealer-vermeer',{id:'dealer-vermeer',name:'ANTIQUA Painting Room · Demo',slug:'antiqua-painting-room-demo',city:bi('Amsterdam','Амстердам'),country:bi('Netherlands','Нидерланды'),since:2026,verified:true,rating:null,responseHours:4,specialties:[bi('Painting','Живопись'),bi('Drawing','Рисунок'),bi('Works on Paper','Работы на бумаге')],about:bi('Fictional demonstration gallery used only to exercise ANTIQUA artwork workflows.','Вымышленная демонстрационная галерея только для проверки сценариев ANTIQUA вокруг произведений искусства.'),policies:bi('Demo environment. No real artworks are offered for sale.','Демонстрационная среда. Реальные произведения здесь не предлагаются к продаже.') }],
 ['dealer-north',{id:'dealer-north',name:'ANTIQUA Works on Paper · Demo',slug:'antiqua-works-on-paper-demo',city:bi('London','Лондон'),country:bi('United Kingdom','Великобритания'),since:2026,verified:true,rating:null,responseHours:12,specialties:[bi('Printmaking','Печатная графика'),bi('Drawing','Рисунок'),bi('Watercolour','Акварель')],about:bi('Fictional demonstration gallery for works-on-paper research, viewing and offer flows.','Вымышленная демонстрационная галерея для исследования графики, запросов на просмотр и предложений цены.'),policies:bi('Demo environment. No real transaction or title transfer occurs.','Демонстрационная среда. Реальная сделка или переход права собственности не происходит.') }],
 ['seller-preview',{id:'seller-preview',name:'ANTIQUA Artist Studio · Demo',slug:'antiqua-artist-studio-demo',city:bi('Paris','Париж'),country:bi('France','Франция'),since:2026,verified:true,rating:null,responseHours:null,specialties:[bi('Contemporary Painting','Современная живопись'),bi('Works on Paper','Работы на бумаге')],about:bi('Fictional studio account used to validate artwork publication and private-sale workflows.','Вымышленный кабинет мастерской для проверки публикации произведений и сценариев частной продажи.'),policies:bi('Preview only.','Только демонстрационная среда.') }]
]);

const demoArtImage=(id,title,variant=0)=>{
 const palettes=[
  ['#d8d2c8','#625d56','#f0ece4'],['#c9c3b9','#3f4744','#ece6dc'],['#d9d4ca','#78695c','#f3efe8'],
  ['#cbc7bd','#4f4b47','#e9e4da'],['#d5cec1','#6a6257','#f1ede5'],['#c7c6c0','#555d60','#eeebe4']
 ];
 const p=palettes[variant%palettes.length],safe=String(title||'ANTIQUA DEMO').replace(/[&<>]/g,'');
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 1500"><rect width="1200" height="1500" fill="${p[2]}"/><rect x="72" y="72" width="1056" height="1356" fill="${p[0]}"/><path d="M130 1100 C330 780 470 1220 690 820 S970 700 1080 380" fill="none" stroke="${p[1]}" stroke-width="64" opacity=".72"/><circle cx="${280+variant*37%500}" cy="${360+variant*53%520}" r="${145+variant*11%120}" fill="${p[1]}" opacity=".24"/><rect x="130" y="1260" width="940" height="92" fill="${p[2]}" opacity=".88"/><text x="160" y="1318" font-family="Georgia,serif" font-size="36" fill="${p[1]}">ANTIQUA DEMO · ${id} · ${safe}</text></svg>`;
 return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)
};

const media=(url)=>[
 {id:'m1',type:'IMAGE',url,role:'PRIMARY',caption:bi('Primary artwork view','Основной вид произведения')},
 {id:'m2',type:'CHECKLIST',role:'DETAIL',caption:bi('Signature / inscription / reverse detail required before publication','До публикации требуется фото подписи / надписи / оборота')},
 {id:'m3',type:'CHECKLIST',role:'CONDITION',caption:bi('Condition detail photograph required before publication','До публикации требуется детальное фото состояния')}
];
const evidence=(source,labelEn,labelRu)=>({id:`ev-${source}-${labelEn.slice(0,5).toLowerCase()}`,source,label:bi(labelEn,labelRu),status:'USER_SUPPLIED'});
const demoDisclosure=bi('Fictional demonstration artwork used only to exercise ANTIQUA workflows. It is not a real artwork or market listing.','Вымышленное демонстрационное произведение только для проверки сценариев ANTIQUA. Это не реальная работа и не реальное рыночное предложение.');

const raw=[
 {n:101,type:'PAINTING',department:bi('Painting','Живопись'),maker:bi('Demo Artist A · fictional','Демо-художник A · вымышленный'),title:bi('Harbour at Blue Hour','Гавань в синий час'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:9000,high:14000,materials:bi('Oil on canvas','Холст, масло'),dimensions:bi('64 × 92 cm','64 × 92 см'),technique:bi('Oil painting','Масляная живопись'),support:bi('Canvas','Холст')},
 {n:102,type:'DRAWING',department:bi('Drawing','Рисунок'),maker:bi('Demo Artist B · fictional','Демо-художник B · вымышленный'),title:bi('Study of Hands','Этюд рук'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:2600,high:4200,materials:bi('Graphite and chalk on paper','Графит и мел на бумаге'),dimensions:bi('42 × 30 cm','42 × 30 см'),technique:bi('Drawing','Рисунок'),support:bi('Paper','Бумага')},
 {n:103,type:'ETCHING',department:bi('Print','Печатная графика'),maker:bi('Demo Artist C · fictional','Демо-художник C · вымышленный'),title:bi('Nocturne with Bridge','Ноктюрн с мостом'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:1800,high:2800,materials:bi('Ink on laid paper','Печатная краска на верже'),dimensions:bi('28 × 39 cm','28 × 39 см'),technique:bi('Etching','Офорт'),support:bi('Paper','Бумага')},
 {n:104,type:'PAINTING',department:bi('Painting','Живопись'),maker:bi('Demo Artist D · fictional','Демо-художник D · вымышленный'),title:bi('River Landscape at Dusk','Речной пейзаж в сумерках'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:12000,high:18000,materials:bi('Oil on canvas','Холст, масло'),dimensions:bi('72 × 104 cm','72 × 104 см'),technique:bi('Oil painting','Масляная живопись'),support:bi('Canvas','Холст')},
 {n:105,type:'WATERCOLOR',department:bi('Works on Paper','Работы на бумаге'),maker:bi('Demo Artist E · fictional','Демо-художник E · вымышленный'),title:bi('Cloud Study','Этюд облаков'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:3500,high:5200,materials:bi('Watercolour over graphite on paper','Акварель поверх графита на бумаге'),dimensions:bi('24 × 33 cm','24 × 33 см'),technique:bi('Watercolour','Акварель'),support:bi('Paper','Бумага')},
 {n:106,type:'LITHOGRAPH',department:bi('Print','Печатная графика'),maker:bi('Demo Artist F · fictional','Демо-художник F · вымышленный'),title:bi('Figures on the Quay','Фигуры на набережной'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:2200,high:3400,materials:bi('Lithographic ink on paper','Литографская краска на бумаге'),dimensions:bi('36 × 49 cm','36 × 49 см'),technique:bi('Lithography','Литография'),support:bi('Paper','Бумага')},
 {n:107,type:'GOUACHE',department:bi('Works on Paper','Работы на бумаге'),maker:bi('Demo Artist G · fictional','Демо-художник G · вымышленный'),title:bi('Interior with Red Chair','Интерьер с красным стулом'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:5000,high:7600,materials:bi('Gouache on paper','Гуашь на бумаге'),dimensions:bi('51 × 38 cm','51 × 38 см'),technique:bi('Gouache','Гуашь'),support:bi('Paper','Бумага')},
 {n:108,type:'ENGRAVING',department:bi('Print','Печатная графика'),maker:bi('Demo Artist H · fictional','Демо-художник H · вымышленный'),title:bi('Garden Architecture','Садовая архитектура'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:3200,high:4800,materials:bi('Ink on paper','Печатная краска на бумаге'),dimensions:bi('31 × 24 cm','31 × 24 см'),technique:bi('Engraving','Гравюра'),support:bi('Paper','Бумага')},
 {n:109,type:'PASTEL',department:bi('Works on Paper','Работы на бумаге'),maker:bi('Demo Artist I · fictional','Демо-художник I · вымышленный'),title:bi('Portrait in Profile','Портрет в профиль'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:6800,high:9000,materials:bi('Pastel on paper','Пастель на бумаге'),dimensions:bi('55 × 41 cm','55 × 41 см'),technique:bi('Pastel','Пастель'),support:bi('Paper','Бумага')},
 {n:110,type:'WOODCUT',department:bi('Print','Печатная графика'),maker:bi('Demo Artist J · fictional','Демо-художник J · вымышленный'),title:bi('Night Garden','Ночной сад'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:2400,high:3600,materials:bi('Relief ink on paper','Высокая печать на бумаге'),dimensions:bi('39 × 29 cm','39 × 29 см'),technique:bi('Woodcut','Ксилография'),support:bi('Paper','Бумага')},
 {n:111,type:'SCREENPRINT',department:bi('Print','Печатная графика'),maker:bi('Demo Artist K · fictional','Демо-художник K · вымышленный'),title:bi('Four Planes','Четыре плоскости'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:3000,high:4600,materials:bi('Screenprint on paper','Шелкография на бумаге'),dimensions:bi('70 × 50 cm','70 × 50 см'),technique:bi('Screenprint','Шелкография'),support:bi('Paper','Бумага')},
 {n:112,type:'MIXED_MEDIA_ON_PAPER',department:bi('Works on Paper','Работы на бумаге'),maker:bi('Demo Artist L · fictional','Демо-художник L · вымышленный'),title:bi('Archive of Lines','Архив линий'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),low:7800,high:11500,materials:bi('Ink, graphite and collage on paper','Тушь, графит и коллаж на бумаге'),dimensions:bi('68 × 48 cm','68 × 48 см'),technique:bi('Mixed media on paper','Смешанная техника на бумаге'),support:bi('Paper','Бумага')}
];

export const lots=raw.map((x,i)=>{
 const image=demoArtImage(x.n,x.title.en,i);
 return{
  id:`lot-${x.n}`,objectId:`AQ-${x.n}-2026`,lotNumber:x.n,artworkType:x.type,department:x.department,maker:x.maker,title:x.title,period:x.period,origin:x.origin,currency:'EUR',estimateLow:x.low,estimateHigh:x.high,image,materials:x.materials,dimensions:x.dimensions,technique:x.technique,support:x.support,
  recordMode:'DEMO_FICTIONAL',demoDisclosure,
  attributionStatus:'CATALOGUED',
  marks:bi(i%2?'No signature or inscription asserted in the fictional demo record.':'A fictional signature location is reserved for UI testing only.','В вымышленной демозаписи подпись или надпись не заявлена.'),
  cataloguing:bi('Fictional demonstration catalogue record. A real publication would require specialist review of attribution, dating, medium, support, dimensions, inscriptions and bibliography.','Вымышленная демонстрационная каталожная запись. Для реальной публикации потребовалась бы экспертная проверка атрибуции, датировки, техники, основы, размеров, надписей и библиографии.'),
  provenance:bi(['Fictional demonstration provenance — not a claim about a real artwork','ANTIQUA workflow record created for product testing'],['Вымышленный демонстрационный провенанс — не утверждение о реальном произведении','Запись ANTIQUA создана для проверки продукта']),
  provenanceTimeline:[{date:'2026',event:bi('Fictional demo record created','Создана вымышленная демозапись'),evidenceStatus:'PLATFORM_RECORD'}],
  condition:bi('Demonstration condition summary only. A real report would map observations to dated high-resolution details.','Только демонстрационная сводка состояния. В реальном отчёте наблюдения должны быть привязаны к датированным детальным изображениям высокого разрешения.'),
  conditionGrade:i%4===0?'B':'A-',restoration:bi('No restoration claim is made for this fictional demonstration artwork.','Для этого вымышленного демонстрационного произведения сведения о реставрации не заявляются.'),
  literature:bi([],[]),exhibitions:bi([],[]),documents:[evidence('DEMO','Demo workflow record','Демонстрационная запись процесса')],media:media(image),
  location:i%2===0?'Amsterdam':'London',exportStatus:'NOT_SCREENED',culturalPropertyStatus:'NOT_SCREENED',passportHash:`preview-${x.n}`,catalogueStatus:'APPROVED'
 }
});

const t0=Date.now();
const seed=[[101,7200,3,5,8500],[102,1800,2,7,2200],[103,1400,4,9,1800],[104,9800,3,11,11000],[105,2800,2,14,3400],[106,1700,2,17,2100]];
export const auctions=seed.map(([n,cur,count,h,res])=>({id:`auc-${n}`,saleId:SALE,lotId:`lot-${n}`,currency:'EUR',baselineBid:cur,currentBid:cur,increment:step(cur),bidCount:count,reservePrice:res,reserveMet:cur>=res,startsAt:new Date(t0-7200000).toISOString(),endsAt:new Date(t0+h*3600000).toISOString(),state:'LIVE',leaderClientId:null,proxyBids:[],history:[{amount:cur,bidder:'Demo bidder •••',time:new Date(t0-1200000).toISOString(),type:'seed'}]}));
export function step(n){return n<1000?50:n<5000?100:n<10000?250:n<20000?500:n<50000?1000:2500;}

export const listings=new Map([
 ['lst-107',{id:'lst-107',lotId:'lot-107',sellerId:'dealer-vermeer',saleType:'BUY_NOW',price:6200,currency:'EUR',negotiable:true,status:'ACTIVE',shippingFrom:'Amsterdam',publishedAt:new Date(t0-86400000*12).toISOString(),views:184,saves:23}],
 ['lst-108',{id:'lst-108',lotId:'lot-108',sellerId:'dealer-north',saleType:'MAKE_OFFER',price:4100,currency:'EUR',negotiable:true,status:'ACTIVE',shippingFrom:'London',publishedAt:new Date(t0-86400000*9).toISOString(),views:119,saves:14}],
 ['lst-109',{id:'lst-109',lotId:'lot-109',sellerId:'seller-preview',saleType:'BUY_NOW',price:8200,currency:'EUR',negotiable:true,status:'ACTIVE',shippingFrom:'Paris',publishedAt:new Date(t0-86400000*6).toISOString(),views:82,saves:9}],
 ['lst-110',{id:'lst-110',lotId:'lot-110',sellerId:'seller-preview',saleType:'MAKE_OFFER',price:3300,currency:'EUR',negotiable:true,status:'ACTIVE',shippingFrom:'Paris',publishedAt:new Date(t0-86400000*4).toISOString(),views:64,saves:11}],
 ['lst-111',{id:'lst-111',lotId:'lot-111',sellerId:'dealer-vermeer',saleType:'BUY_NOW',price:4200,currency:'EUR',negotiable:false,status:'ACTIVE',shippingFrom:'Amsterdam',publishedAt:new Date(t0-86400000*7).toISOString(),views:96,saves:8}],
 ['lst-112',{id:'lst-112',lotId:'lot-112',sellerId:'dealer-north',saleType:'BUY_NOW',price:9800,currency:'EUR',negotiable:true,status:'ACTIVE',shippingFrom:'London',publishedAt:new Date(t0-86400000*3).toISOString(),views:141,saves:19}]
]);

export const draftItems=new Map([
 ['draft-1',{id:'draft-1',sellerId:'seller-preview',status:'CHANGES_REQUESTED',saleRoute:'SHOP',createdAt:new Date(t0-86400000*2).toISOString(),updatedAt:new Date(t0-3600000*5).toISOString(),artworkType:'DRAWING',title:bi('Demo drawing: seated figure','Демо-рисунок: сидящая фигура'),category:bi('Drawing','Рисунок'),maker:bi('Demo Artist M · fictional','Демо-художник M · вымышленный'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),materials:bi('Charcoal on paper','Уголь на бумаге'),dimensions:bi('52 × 38 cm','52 × 38 см'),description:demoDisclosure,provenance:demoDisclosure,condition:bi('Demo condition description; detail mapping is incomplete.','Демонстрационное описание состояния; привязка деталей не завершена.'),price:2400,estimateLow:1800,estimateHigh:2600,shippingFrom:'Paris',media:[{url:demoArtImage('draft-1','Seated figure',12),role:'PRIMARY'}],documents:[],reviewNotes:[bi('Add clear photographs of signature/inscriptions, reverse, edges and condition details.','Добавьте чёткие фотографии подписи/надписей, оборота, краёв и деталей состояния.')]}],
 ['draft-2',{id:'draft-2',sellerId:'seller-preview',status:'DRAFT',saleRoute:'AUCTION',createdAt:new Date(t0-86400000).toISOString(),updatedAt:new Date(t0-3600000).toISOString(),artworkType:'PRINT',title:bi('Demo print: two figures','Демо-эстамп: две фигуры'),category:bi('Print','Печатная графика'),maker:bi('Demo Artist N · fictional','Демо-художник N · вымышленный'),period:bi('Demonstration record, 2026','Демонстрационная запись, 2026'),origin:bi('Fictional European context','Вымышленный европейский контекст'),materials:bi('Ink on paper','Печатная краска на бумаге'),dimensions:bi('',''),description:demoDisclosure,provenance:demoDisclosure,condition:bi('',''),price:0,estimateLow:1200,estimateHigh:1800,shippingFrom:'Paris',media:[],documents:[],reviewNotes:[]}]
]);

export const offers=new Map();
export const orders=new Map();
export const messages=new Map();
export const clients=new Map();
export const idem=new Map();
