import {db,lots,listings,auctions,uid,now,bi,notify} from './runtime-v09.mjs';
import {enqueueOutboxTx} from './outbox-v15.mjs';

const clone=x=>x==null?x:structuredClone(x);
const iso=v=>v?.toISOString?.()||v||null;
const fail=(status,code,message)=>{const e=new Error(message);e.status=status;e.code=code;throw e};
const PUBLIC=new Set(['PREVIEW','LIVE','ARCHIVED']);
const MUTABLE=new Set(['DRAFT','SCHEDULED','PREVIEW']);
const transitions={DRAFT:new Set(['SCHEDULED']),SCHEDULED:new Set(['PREVIEW']),PREVIEW:new Set(['LIVE']),LIVE:new Set(['ARCHIVED']),ARCHIVED:new Set()};
const mem={drops:new Map(),items:new Map(),follows:new Map(),events:new Map()};

function textPair(v,ru=''){if(v&&typeof v==='object')return clone(v);const x=String(v||'');return{en:x,ru:String(ru||x)}}
function mapDrop(r){return r?{id:r.id,slug:r.slug,title:r.title||{},subtitle:r.subtitle||{},statement:r.statement||{},curatorAccountId:r.curator_account_id??r.curatorAccountId??null,curatorLabel:r.curator_label??r.curatorLabel??{},coverObjectId:r.cover_object_id??r.coverObjectId??null,status:r.status,version:Number(r.version||1),previewAt:iso(r.preview_at??r.previewAt),releaseAt:iso(r.release_at??r.releaseAt),archiveAt:iso(r.archive_at??r.archiveAt),metadata:r.metadata||{},createdAt:iso(r.created_at??r.createdAt),updatedAt:iso(r.updated_at??r.updatedAt)}:null}
function mapItem(r){return{dropId:r.drop_id??r.dropId,objectId:r.object_id??r.objectId,sortOrder:Number(r.sort_order??r.sortOrder??0),releaseLimit:Number(r.release_limit??r.releaseLimit??1),merchandising:r.merchandising||{},createdAt:iso(r.created_at??r.createdAt),updatedAt:iso(r.updated_at??r.updatedAt)}}
function eventList(id){if(!mem.events.has(id))mem.events.set(id,[]);return mem.events.get(id)}
function followKey(dropId,accountId){return dropId+'|'+accountId}
function actionId(body={}){const x=String(body.clientActionId||'').trim();if(!x)fail(400,'CLIENT_ACTION_ID_REQUIRED','clientActionId is required');if(x.length>160)fail(400,'CLIENT_ACTION_ID_INVALID','clientActionId is too long');return x}
function expected(body,current){const v=Number(body.expectedVersion);if(!Number.isInteger(v)||v<1)fail(400,'EXPECTED_VERSION_REQUIRED','expectedVersion is required');if(v!==Number(current))fail(409,'STALE_DROP_VERSION','Drop changed; reload before acting')}
function validSlug(v){return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(String(v||''))}
function time(v,name,{required=false}={}){if(v==null||v===''){if(required)fail(400,'DROP_TIME_REQUIRED',name+' is required');return null}const d=new Date(v);if(Number.isNaN(d.getTime()))fail(400,'DROP_TIME_INVALID',name+' is invalid');return d.toISOString()}
function scheduleTimes(current,body={}){const previewAt=time(body.previewAt??current.previewAt,'previewAt',{required:true}),releaseAt=time(body.releaseAt??current.releaseAt,'releaseAt',{required:true}),archiveAt=time(body.archiveAt??current.archiveAt,'archiveAt');if(Date.parse(releaseAt)<Date.parse(previewAt))fail(400,'DROP_TIME_ORDER','releaseAt must be at or after previewAt');if(archiveAt&&Date.parse(archiveAt)<=Date.parse(releaseAt))fail(400,'DROP_TIME_ORDER','archiveAt must be after releaseAt');return{previewAt,releaseAt,archiveAt}}

function seedMemory(){if(mem.drops.size)return;const t=Date.now(),drop={id:'drop-objects-of-power',slug:'objects-of-power',title:bi('Objects of Power','Предметы власти'),subtitle:bi('Objects designed to signal authority, ritual and presence','Предметы, созданные для выражения власти, ритуала и присутствия'),statement:bi('A release about how objects acquire social force through material, scale and context.','Выпуск о том, как предметы обретают социальную силу через материал, масштаб и контекст.'),curatorAccountId:null,curatorLabel:bi('ANTIQUA Curatorial','Кураторская команда ANTIQUA'),coverObjectId:'lot-101',status:'LIVE',version:1,previewAt:new Date(t-2*86400000).toISOString(),releaseAt:new Date(t-86400000).toISOString(),archiveAt:new Date(t+6*86400000).toISOString(),metadata:{seed:true},createdAt:new Date(t-3*86400000).toISOString(),updatedAt:new Date(t-86400000).toISOString()};mem.drops.set(drop.id,drop);mem.items.set(drop.id,['lot-101','lot-106','lot-110','lot-112'].map((objectId,i)=>({dropId:drop.id,objectId,sortOrder:i+1,releaseLimit:1,merchandising:{},createdAt:drop.createdAt,updatedAt:drop.updatedAt})));eventList(drop.id).push({id:'dev-'+drop.id,dropId:drop.id,version:1,eventType:'RELEASED',actorAccountId:null,actorRole:'SYSTEM',fromStatus:'PREVIEW',toStatus:'LIVE',clientActionId:null,metadata:{seed:true},createdAt:drop.updatedAt})}
seedMemory();

export function dropsCapabilities(){return{contractVersion:'v29',separateFromExhibitions:true,saleAuthority:'LISTING_OR_AUCTION',lifecycle:['DRAFT','SCHEDULED','PREVIEW','LIVE','ARCHIVED'],optimisticLocking:true,immutableHistory:true,followNotifications:'EXACTLY_ONCE_OUTBOX_POSTGRES',scheduledRelease:'WORKER',inventoryMeaning:'DROP_RELEASE_LIMIT_NOT_LIVE_AVAILABILITY'}}

function memoryObject(id){const o=lots.find(x=>x.id===id);if(!o)return null;return{id:o.id,objectId:o.objectId,title:o.title,maker:o.maker,department:o.department,period:o.period,origin:o.origin,image:o.image,conditionGrade:o.conditionGrade}}
function memoryCommerce(id){const li=[...listings.values()].find(x=>x.lotId===id&&['ACTIVE','RESERVED'].includes(x.status))||null,au=auctions.find(x=>x.lotId===id&&x.state!=='CLOSED'&&Date.parse(x.endsAt)>Date.now())||null;if(au)return{available:true,authority:'AUCTION',auctionId:au.id,status:au.state||'LIVE',price:Number(au.currentBid),currency:au.currency};if(li)return{available:li.status==='ACTIVE',authority:'LISTING',listingId:li.id,status:li.status,saleType:li.saleType,price:Number(li.price),currency:li.currency};return{available:false,authority:null,status:'UNAVAILABLE',price:null,currency:null}}
async function pgItems(dropId){const rows=(await db.pool.query(`SELECT di.*,o.object_code,o.passport,o.publication_status,o.catalogue_status,
 l.id AS listing_id,l.status AS listing_status,l.payload AS listing_payload,
 a.id AS auction_id,a.status AS auction_status,a.current_bid,a.ends_at,a.state AS auction_state
 FROM drop_items di JOIN objects o ON o.id=di.object_id
 LEFT JOIN LATERAL (SELECT id,status,payload FROM listings WHERE object_id=o.id AND status IN('ACTIVE','RESERVED') ORDER BY updated_at DESC,id LIMIT 1) l ON true
 LEFT JOIN LATERAL (SELECT id,status,current_bid,ends_at,state FROM auctions WHERE object_id=o.id ORDER BY (ends_at>clock_timestamp()) DESC,updated_at DESC,id LIMIT 1) a ON true
 WHERE di.drop_id=$1 ORDER BY di.sort_order,di.object_id`,[dropId])).rows;
 return rows.map(r=>{const p=r.passport||{},auctionOpen=Boolean(r.auction_id&&r.ends_at&&new Date(r.ends_at)>new Date()&&String(r.auction_state||r.auction_status)!=='CLOSED'),listing=Boolean(r.listing_id),commerce=auctionOpen?{available:true,authority:'AUCTION',auctionId:r.auction_id,status:r.auction_state||r.auction_status,price:Number(r.current_bid),currency:r.auction_state?.currency||p.currency||'EUR'}:listing?{available:r.listing_status==='ACTIVE',authority:'LISTING',listingId:r.listing_id,status:r.listing_status,saleType:r.listing_payload?.saleType,price:Number(r.listing_payload?.price),currency:r.listing_payload?.currency||p.currency||'EUR'}:{available:false,authority:null,status:'UNAVAILABLE',price:null,currency:null};return{...mapItem(r),object:{id:r.object_id,objectId:r.object_code||p.objectId||r.object_id,title:p.title||{},maker:p.maker||{},department:p.department||{},period:p.period||{},origin:p.origin||{},image:p.image||null,conditionGrade:p.conditionGrade||null},commerce}})
}
async function itemsFor(dropId){if(db.kind==='POSTGRES')return pgItems(dropId);return(mem.items.get(dropId)||[]).map(x=>({...clone(x),object:memoryObject(x.objectId),commerce:memoryCommerce(x.objectId)})).filter(x=>x.object)}
async function followed(dropId,account){if(!account)return false;if(db.kind==='POSTGRES')return Boolean((await db.pool.query('SELECT 1 FROM drop_follows WHERE drop_id=$1 AND account_id=$2',[dropId,account.id])).rowCount);return mem.follows.has(followKey(dropId,account.id))}
async function publicDrop(d,account=null){if(!d)return null;return{...clone(d),items:await itemsFor(d.id),followed:await followed(d.id,account),capabilities:{saleAuthority:'LISTING_OR_AUCTION',releaseLimitIsNotAvailability:true}}}

export async function listPublicDrops(account=null){let rows;if(db.kind==='POSTGRES')rows=(await db.pool.query("SELECT * FROM drops WHERE status IN('PREVIEW','LIVE','ARCHIVED') ORDER BY CASE status WHEN 'LIVE' THEN 0 WHEN 'PREVIEW' THEN 1 ELSE 2 END,release_at DESC NULLS LAST,updated_at DESC")).rows.map(mapDrop);else rows=[...mem.drops.values()].filter(x=>PUBLIC.has(x.status)).sort((a,b)=>(a.status==='LIVE'?0:a.status==='PREVIEW'?1:2)-(b.status==='LIVE'?0:b.status==='PREVIEW'?1:2)||String(b.releaseAt||'').localeCompare(String(a.releaseAt||'')));const out=[];for(const d of rows)out.push(await publicDrop(d,account));return out}
export async function getPublicDrop(idOrSlug,account=null){let d;if(db.kind==='POSTGRES'){const r=(await db.pool.query("SELECT * FROM drops WHERE (id=$1 OR slug=$1) AND status IN('PREVIEW','LIVE','ARCHIVED')",[String(idOrSlug)])).rows[0];d=mapDrop(r)}else d=[...mem.drops.values()].find(x=>(x.id===idOrSlug||x.slug===idOrSlug)&&PUBLIC.has(x.status));return d?publicDrop(d,account):null}
export async function getDropForOperator(id){if(db.kind==='POSTGRES'){const r=(await db.pool.query('SELECT * FROM drops WHERE id=$1',[id])).rows[0];if(!r)return null;const d=mapDrop(r),events=(await db.pool.query('SELECT * FROM drop_events WHERE drop_id=$1 ORDER BY version',[id])).rows.map(e=>({id:e.id,dropId:e.drop_id,version:Number(e.version),eventType:e.event_type,actorAccountId:e.actor_account_id,actorRole:e.actor_role,fromStatus:e.from_status,toStatus:e.to_status,clientActionId:e.client_action_id,metadata:e.metadata||{},createdAt:iso(e.created_at)}));return{...d,items:await itemsFor(id),events}}const d=mem.drops.get(id);return d?{...clone(d),items:await itemsFor(id),events:clone(eventList(id))}:null}
export async function listDropsForOperator(){if(db.kind==='POSTGRES')return(await db.pool.query('SELECT * FROM drops ORDER BY updated_at DESC')).rows.map(mapDrop);return[...mem.drops.values()].map(clone).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}

async function validateReadyPg(cx,id){const d=mapDrop((await cx.query('SELECT * FROM drops WHERE id=$1',[id])).rows[0]),items=(await cx.query(`SELECT di.object_id,o.publication_status,o.catalogue_status FROM drop_items di JOIN objects o ON o.id=di.object_id WHERE di.drop_id=$1 ORDER BY di.sort_order`,[id])).rows;if(!items.length)fail(409,'DROP_EMPTY','Drop requires at least one object');const bad=items.filter(x=>x.publication_status!=='PUBLIC'||!['APPROVED','PUBLISHED'].includes(String(x.catalogue_status)));if(bad.length)fail(409,'DROP_OBJECT_NOT_PUBLIC','All drop objects must be public and catalogue-approved');if(d.coverObjectId&&!items.some(x=>x.object_id===d.coverObjectId))fail(409,'DROP_COVER_NOT_MEMBER','Cover object must belong to the drop');return{d,items}}
function validateReadyMemory(d){const items=mem.items.get(d.id)||[];if(!items.length)fail(409,'DROP_EMPTY','Drop requires at least one object');if(d.coverObjectId&&!items.some(x=>x.objectId===d.coverObjectId))fail(409,'DROP_COVER_NOT_MEMBER','Cover object must belong to the drop');for(const x of items){const o=lots.find(y=>y.id===x.objectId);if(!o||!['APPROVED','PUBLISHED'].includes(String(o.catalogueStatus)))fail(409,'DROP_OBJECT_NOT_PUBLIC','All drop objects must be public and catalogue-approved')}}

export async function createDrop(account,body={}){const clientActionId=actionId(body),slug=String(body.slug||'').trim().toLowerCase();if(!validSlug(slug))fail(400,'DROP_SLUG_INVALID','slug must be lowercase words separated by hyphens');const title=textPair(body.titleEn||body.title,body.titleRu);if(!String(title.en||title.ru||'').trim())fail(400,'DROP_TITLE_REQUIRED','Drop title is required');const ts=now(),drop={id:uid('drop'),slug,title,subtitle:textPair(body.subtitleEn||body.subtitle,body.subtitleRu),statement:textPair(body.statementEn||body.statement,body.statementRu),curatorAccountId:body.curatorAccountId||null,curatorLabel:textPair(body.curatorLabelEn||body.curatorLabel,body.curatorLabelRu),coverObjectId:body.coverObjectId||null,status:'DRAFT',version:1,previewAt:null,releaseAt:null,archiveAt:null,metadata:body.metadata&&typeof body.metadata==='object'?body.metadata:{},createdAt:ts,updatedAt:ts};
 if(db.kind!=='POSTGRES'){for(const d of mem.drops.values())if(d.slug===slug)fail(409,'DROP_SLUG_EXISTS','Drop slug already exists');const replay=[...mem.events.values()].flat().find(e=>e.actorAccountId===account.id&&e.clientActionId===clientActionId);if(replay)return{drop:await getDropForOperator(replay.dropId),idempotent:true};mem.drops.set(drop.id,drop);eventList(drop.id).push({id:uid('dev'),dropId:drop.id,version:1,eventType:'CREATED',actorAccountId:account.id,actorRole:'OPERATOR',fromStatus:null,toStatus:'DRAFT',clientActionId,metadata:{slug},createdAt:ts});return{drop:await getDropForOperator(drop.id),idempotent:false}}
 const cx=await db.pool.connect();try{await cx.query('BEGIN');const prior=(await cx.query('SELECT drop_id FROM drop_events WHERE actor_account_id=$1 AND client_action_id=$2',[account.id,clientActionId])).rows[0];if(prior){await cx.query('COMMIT');return{drop:await getDropForOperator(prior.drop_id),idempotent:true}}await cx.query('INSERT INTO drops(id,slug,title,subtitle,statement,curator_account_id,curator_label,cover_object_id,status,version,metadata,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,1,$10,$11,$11)',[drop.id,drop.slug,drop.title,drop.subtitle,drop.statement,drop.curatorAccountId,drop.curatorLabel,drop.coverObjectId,'DRAFT',drop.metadata,ts]);await cx.query("INSERT INTO drop_events(id,drop_id,version,event_type,actor_account_id,actor_role,from_status,to_status,client_action_id,metadata,created_at) VALUES($1,$2,1,'CREATED',$3,'OPERATOR',NULL,'DRAFT',$4,$5,$6)",[uid('dev'),drop.id,account.id,clientActionId,{slug},ts]);await cx.query('COMMIT');return{drop:await getDropForOperator(drop.id),idempotent:false}}catch(e){try{await cx.query('ROLLBACK')}catch{}if(e?.code==='23505'&&String(e.constraint||'').includes('slug'))fail(409,'DROP_SLUG_EXISTS','Drop slug already exists');throw e}finally{cx.release()}}

function applyPatch(d,body){if(body.title||body.titleEn||body.titleRu)d.title=textPair(body.titleEn||body.title||d.title,body.titleRu||d.title?.ru);if(body.subtitle||body.subtitleEn||body.subtitleRu)d.subtitle=textPair(body.subtitleEn||body.subtitle||d.subtitle,body.subtitleRu||d.subtitle?.ru);if(body.statement||body.statementEn||body.statementRu)d.statement=textPair(body.statementEn||body.statement||d.statement,body.statementRu||d.statement?.ru);if(body.curatorLabel||body.curatorLabelEn||body.curatorLabelRu)d.curatorLabel=textPair(body.curatorLabelEn||body.curatorLabel||d.curatorLabel,body.curatorLabelRu||d.curatorLabel?.ru);if('coverObjectId' in body)d.coverObjectId=body.coverObjectId||null;if(body.metadata&&typeof body.metadata==='object')d.metadata=body.metadata;return d}
export async function updateDrop(account,id,body={}){const clientActionId=actionId(body);if(db.kind!=='POSTGRES'){const d=mem.drops.get(id);if(!d)fail(404,'DROP_NOT_FOUND','Drop not found');if(!MUTABLE.has(d.status))fail(409,'DROP_IMMUTABLE_PHASE','Drop metadata is locked after release');const prior=eventList(id).find(e=>e.actorAccountId===account.id&&e.clientActionId===clientActionId);if(prior)return{drop:await getDropForOperator(id),idempotent:true};expected(body,d.version);const before=d.status;applyPatch(d,body);d.version++;d.updatedAt=now();eventList(id).push({id:uid('dev'),dropId:id,version:d.version,eventType:'UPDATED',actorAccountId:account.id,actorRole:'OPERATOR',fromStatus:before,toStatus:before,clientActionId,metadata:{},createdAt:d.updatedAt});return{drop:await getDropForOperator(id),idempotent:false}}
 const early=(await db.pool.query('SELECT drop_id FROM drop_events WHERE actor_account_id=$1 AND client_action_id=$2',[account.id,clientActionId])).rows[0];if(early){if(early.drop_id!==id)fail(409,'CLIENT_ACTION_ID_CONFLICT','clientActionId belongs to another drop');return{drop:await getDropForOperator(id),idempotent:true}}const cx=await db.pool.connect();try{await cx.query('BEGIN');const row=(await cx.query('SELECT * FROM drops WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)fail(404,'DROP_NOT_FOUND','Drop not found');let d=mapDrop(row);if(!MUTABLE.has(d.status))fail(409,'DROP_IMMUTABLE_PHASE','Drop metadata is locked after release');expected(body,d.version);const before=d.status;applyPatch(d,body);d.version++;d.updatedAt=now();await cx.query('UPDATE drops SET title=$2,subtitle=$3,statement=$4,curator_label=$5,cover_object_id=$6,metadata=$7,version=$8,updated_at=$9 WHERE id=$1',[id,d.title,d.subtitle,d.statement,d.curatorLabel,d.coverObjectId,d.metadata,d.version,d.updatedAt]);await cx.query("INSERT INTO drop_events(id,drop_id,version,event_type,actor_account_id,actor_role,from_status,to_status,client_action_id,metadata,created_at) VALUES($1,$2,$3,'UPDATED',$4,'OPERATOR',$5,$5,$6,'{}'::jsonb,$7)",[uid('dev'),id,d.version,account.id,before,clientActionId,d.updatedAt]);await cx.query('COMMIT');return{drop:await getDropForOperator(id),idempotent:false}}catch(e){try{await cx.query('ROLLBACK')}catch{}throw e}finally{cx.release()}}

export async function upsertDropItem(account,id,body={}){const clientActionId=actionId(body),objectId=String(body.objectId||''),sortOrder=Math.max(0,Math.trunc(Number(body.sortOrder)||0)),releaseLimit=Math.max(1,Math.min(1000,Math.trunc(Number(body.releaseLimit)||1))),merchandising=body.merchandising&&typeof body.merchandising==='object'?body.merchandising:{};if(!objectId)fail(400,'DROP_OBJECT_REQUIRED','objectId is required');
 if(db.kind!=='POSTGRES'){const d=mem.drops.get(id);if(!d)fail(404,'DROP_NOT_FOUND','Drop not found');if(!MUTABLE.has(d.status))fail(409,'DROP_IMMUTABLE_PHASE','Drop items are locked after release');const prior=eventList(id).find(e=>e.actorAccountId===account.id&&e.clientActionId===clientActionId);if(prior)return{drop:await getDropForOperator(id),idempotent:true};expected(body,d.version);if(!lots.some(x=>x.id===objectId))fail(404,'OBJECT_NOT_FOUND','Object not found');const xs=mem.items.get(id)||[],at=xs.findIndex(x=>x.objectId===objectId),item={dropId:id,objectId,sortOrder,releaseLimit,merchandising,createdAt:at>=0?xs[at].createdAt:now(),updatedAt:now()};if(at>=0)xs[at]=item;else xs.push(item);if(xs.some((x,i)=>i!==(at>=0?at:xs.length-1)&&x.sortOrder===sortOrder))fail(409,'DROP_SORT_CONFLICT','sortOrder already used');mem.items.set(id,xs);d.version++;d.updatedAt=now();eventList(id).push({id:uid('dev'),dropId:id,version:d.version,eventType:'ITEM_UPSERTED',actorAccountId:account.id,actorRole:'OPERATOR',fromStatus:d.status,toStatus:d.status,clientActionId,metadata:{objectId,sortOrder,releaseLimit},createdAt:d.updatedAt});return{drop:await getDropForOperator(id),idempotent:false}}
 const cx=await db.pool.connect();try{await cx.query('BEGIN');const replay=(await cx.query('SELECT drop_id FROM drop_events WHERE actor_account_id=$1 AND client_action_id=$2',[account.id,clientActionId])).rows[0];if(replay){if(replay.drop_id!==id)fail(409,'CLIENT_ACTION_ID_CONFLICT','clientActionId belongs to another drop');await cx.query('COMMIT');return{drop:await getDropForOperator(id),idempotent:true}}const row=(await cx.query('SELECT * FROM drops WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)fail(404,'DROP_NOT_FOUND','Drop not found');const d=mapDrop(row);if(!MUTABLE.has(d.status))fail(409,'DROP_IMMUTABLE_PHASE','Drop items are locked after release');expected(body,d.version);const exists=(await cx.query('SELECT 1 FROM objects WHERE id=$1',[objectId])).rowCount;if(!exists)fail(404,'OBJECT_NOT_FOUND','Object not found');await cx.query('INSERT INTO drop_items(drop_id,object_id,sort_order,release_limit,merchandising) VALUES($1,$2,$3,$4,$5) ON CONFLICT(drop_id,object_id) DO UPDATE SET sort_order=excluded.sort_order,release_limit=excluded.release_limit,merchandising=excluded.merchandising,updated_at=now()',[id,objectId,sortOrder,releaseLimit,merchandising]);const version=d.version+1,ts=now();await cx.query('UPDATE drops SET version=$2,updated_at=$3 WHERE id=$1',[id,version,ts]);await cx.query("INSERT INTO drop_events(id,drop_id,version,event_type,actor_account_id,actor_role,from_status,to_status,client_action_id,metadata,created_at) VALUES($1,$2,$3,'ITEM_UPSERTED',$4,'OPERATOR',$5,$5,$6,$7,$8)",[uid('dev'),id,version,account.id,d.status,clientActionId,{objectId,sortOrder,releaseLimit},ts]);await cx.query('COMMIT');return{drop:await getDropForOperator(id),idempotent:false}}catch(e){try{await cx.query('ROLLBACK')}catch{}if(e?.code==='23505')fail(409,'DROP_SORT_CONFLICT','sortOrder already used');throw e}finally{cx.release()}}

export async function removeDropItem(account,id,objectId,body={}){const clientActionId=actionId(body);objectId=String(objectId||'');if(db.kind!=='POSTGRES'){const d=mem.drops.get(id);if(!d)fail(404,'DROP_NOT_FOUND','Drop not found');if(!MUTABLE.has(d.status))fail(409,'DROP_IMMUTABLE_PHASE','Drop items are locked after release');const prior=eventList(id).find(e=>e.actorAccountId===account.id&&e.clientActionId===clientActionId);if(prior)return{drop:await getDropForOperator(id),idempotent:true};expected(body,d.version);const xs=mem.items.get(id)||[],next=xs.filter(x=>x.objectId!==objectId);if(next.length===xs.length)fail(404,'DROP_ITEM_NOT_FOUND','Drop item not found');mem.items.set(id,next);if(d.coverObjectId===objectId)d.coverObjectId=null;d.version++;d.updatedAt=now();eventList(id).push({id:uid('dev'),dropId:id,version:d.version,eventType:'ITEM_REMOVED',actorAccountId:account.id,actorRole:'OPERATOR',fromStatus:d.status,toStatus:d.status,clientActionId,metadata:{objectId},createdAt:d.updatedAt});return{drop:await getDropForOperator(id),idempotent:false}}
 const cx=await db.pool.connect();try{await cx.query('BEGIN');const replay=(await cx.query('SELECT drop_id FROM drop_events WHERE actor_account_id=$1 AND client_action_id=$2',[account.id,clientActionId])).rows[0];if(replay){if(replay.drop_id!==id)fail(409,'CLIENT_ACTION_ID_CONFLICT','clientActionId belongs to another drop');await cx.query('COMMIT');return{drop:await getDropForOperator(id),idempotent:true}}const row=(await cx.query('SELECT * FROM drops WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)fail(404,'DROP_NOT_FOUND','Drop not found');const d=mapDrop(row);if(!MUTABLE.has(d.status))fail(409,'DROP_IMMUTABLE_PHASE','Drop items are locked after release');expected(body,d.version);const del=await cx.query('DELETE FROM drop_items WHERE drop_id=$1 AND object_id=$2 RETURNING object_id',[id,objectId]);if(!del.rowCount)fail(404,'DROP_ITEM_NOT_FOUND','Drop item not found');if(d.coverObjectId===objectId)await cx.query('UPDATE drops SET cover_object_id=NULL WHERE id=$1',[id]);const version=d.version+1,ts=now();await cx.query('UPDATE drops SET version=$2,updated_at=$3 WHERE id=$1',[id,version,ts]);await cx.query("INSERT INTO drop_events(id,drop_id,version,event_type,actor_account_id,actor_role,from_status,to_status,client_action_id,metadata,created_at) VALUES($1,$2,$3,'ITEM_REMOVED',$4,'OPERATOR',$5,$5,$6,$7,$8)",[uid('dev'),id,version,account.id,d.status,clientActionId,{objectId},ts]);await cx.query('COMMIT');return{drop:await getDropForOperator(id),idempotent:false}}catch(e){try{await cx.query('ROLLBACK')}catch{}throw e}finally{cx.release()}}

async function enqueueReleaseTx(cx,d,version){const followers=(await cx.query('SELECT account_id FROM drop_follows WHERE drop_id=$1 ORDER BY account_id',[d.id])).rows;let queued=0;for(const f of followers){const payload={accountId:f.account_id,type:'DROP_RELEASED',data:{dropId:d.id,slug:d.slug,title:d.title,releaseAt:d.releaseAt}};const out=await enqueueOutboxTx(cx,{topic:'NOTIFICATION',aggregateType:'DROP',aggregateId:d.id,payload,idempotencyKey:`notification:drop-released:${d.id}:${f.account_id}:v${version}`});if(!out.idempotent)queued++}return{followers:followers.length,queued}}
function transitionEvent(target){return target==='SCHEDULED'?'SCHEDULED':target==='PREVIEW'?'PREVIEWED':target==='LIVE'?'RELEASED':'ARCHIVED'}
async function transitionInternal(actor,id,target,body={}){target=String(target||'').toUpperCase();const actorRole=actor?'OPERATOR':'SYSTEM',clientActionId=actor?actionId(body):null;
 if(db.kind!=='POSTGRES'){const d=mem.drops.get(id);if(!d)fail(404,'DROP_NOT_FOUND','Drop not found');if(actor){const prior=eventList(id).find(e=>e.actorAccountId===actor.id&&e.clientActionId===clientActionId);if(prior)return{drop:await getDropForOperator(id),idempotent:true,notifications:{followers:0,queued:0}};expected(body,d.version)}if(!transitions[d.status]?.has(target))fail(409,'DROP_TRANSITION_INVALID',`Cannot move drop from ${d.status} to ${target}`);const before=d.status;if(target==='SCHEDULED'){validateReadyMemory(d);Object.assign(d,scheduleTimes(d,body))}if(target==='PREVIEW'&&Date.now()<Date.parse(d.previewAt))fail(409,'DROP_PREVIEW_NOT_DUE','Preview time has not arrived');if(target==='LIVE'&&Date.now()<Date.parse(d.releaseAt))fail(409,'DROP_RELEASE_NOT_DUE','Release time has not arrived');d.status=target;d.version++;d.updatedAt=now();eventList(id).push({id:uid('dev'),dropId:id,version:d.version,eventType:transitionEvent(target),actorAccountId:actor?.id||null,actorRole,fromStatus:before,toStatus:target,clientActionId,metadata:{},createdAt:d.updatedAt});let notifications={followers:0,queued:0};if(target==='LIVE'){const followers=[...mem.follows.values()].filter(x=>x.dropId===id);for(const f of followers)await notify(f.accountId,'DROP_RELEASED',{dropId:d.id,slug:d.slug,title:d.title,releaseAt:d.releaseAt});notifications={followers:followers.length,queued:followers.length}}return{drop:await getDropForOperator(id),idempotent:false,notifications}}
 const early=actor?(await db.pool.query('SELECT drop_id FROM drop_events WHERE actor_account_id=$1 AND client_action_id=$2',[actor.id,clientActionId])).rows[0]:null;if(early){if(early.drop_id!==id)fail(409,'CLIENT_ACTION_ID_CONFLICT','clientActionId belongs to another drop');return{drop:await getDropForOperator(id),idempotent:true,notifications:{followers:0,queued:0}}}const cx=await db.pool.connect();try{await cx.query('BEGIN');const row=(await cx.query('SELECT * FROM drops WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)fail(404,'DROP_NOT_FOUND','Drop not found');let d=mapDrop(row);if(actor)expected(body,d.version);if(!transitions[d.status]?.has(target))fail(409,'DROP_TRANSITION_INVALID',`Cannot move drop from ${d.status} to ${target}`);const before=d.status;if(target==='SCHEDULED'){await validateReadyPg(cx,id);Object.assign(d,scheduleTimes(d,body))}if(target==='PREVIEW'&&Date.now()<Date.parse(d.previewAt))fail(409,'DROP_PREVIEW_NOT_DUE','Preview time has not arrived');if(target==='LIVE'&&Date.now()<Date.parse(d.releaseAt))fail(409,'DROP_RELEASE_NOT_DUE','Release time has not arrived');d.status=target;d.version++;d.updatedAt=now();await cx.query('UPDATE drops SET status=$2,version=$3,preview_at=$4,release_at=$5,archive_at=$6,updated_at=$7 WHERE id=$1',[id,d.status,d.version,d.previewAt,d.releaseAt,d.archiveAt,d.updatedAt]);await cx.query('INSERT INTO drop_events(id,drop_id,version,event_type,actor_account_id,actor_role,from_status,to_status,client_action_id,metadata,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[uid('dev'),id,d.version,transitionEvent(target),actor?.id||null,actorRole,before,target,clientActionId,{},d.updatedAt]);let notifications={followers:0,queued:0};if(target==='LIVE')notifications=await enqueueReleaseTx(cx,d,d.version);await cx.query('COMMIT');return{drop:await getDropForOperator(id),idempotent:false,notifications}}catch(e){try{await cx.query('ROLLBACK')}catch{}throw e}finally{cx.release()}}
export async function transitionDrop(account,id,target,body={}){return transitionInternal(account,id,target,body)}

export async function listDropFollows(account){if(db.kind==='POSTGRES')return(await db.pool.query('SELECT drop_id,followed_at FROM drop_follows WHERE account_id=$1 ORDER BY followed_at DESC',[account.id])).rows.map(r=>({dropId:r.drop_id,followedAt:iso(r.followed_at)}));return[...mem.follows.values()].filter(x=>x.accountId===account.id).map(clone).sort((a,b)=>String(b.followedAt).localeCompare(String(a.followedAt)))}

export async function setDropFollow(account,id,enabled=true){enabled=enabled!==false;let d;if(db.kind==='POSTGRES'){d=mapDrop((await db.pool.query("SELECT * FROM drops WHERE id=$1 AND status IN('PREVIEW','LIVE')",[id])).rows[0]);if(!d)fail(404,'DROP_NOT_FOLLOWABLE','Drop is not available to follow');if(enabled)await db.pool.query('INSERT INTO drop_follows(drop_id,account_id) VALUES($1,$2) ON CONFLICT(drop_id,account_id) DO NOTHING',[id,account.id]);else await db.pool.query('DELETE FROM drop_follows WHERE drop_id=$1 AND account_id=$2',[id,account.id]);return{dropId:id,followed:enabled}}d=mem.drops.get(id);if(!d||!['PREVIEW','LIVE'].includes(d.status))fail(404,'DROP_NOT_FOLLOWABLE','Drop is not available to follow');const k=followKey(id,account.id);if(enabled)mem.follows.set(k,{dropId:id,accountId:account.id,followedAt:now()});else mem.follows.delete(k);return{dropId:id,followed:enabled}}

export async function advanceDueDrops(){if(db.kind!=='POSTGRES')return{changed:0,previewed:0,released:0,archived:0,reason:'POSTGRES_REQUIRED'};let changed=0,previewed=0,released=0,archived=0;for(let pass=0;pass<3;pass++){const rows=(await db.pool.query(`SELECT id,status,version FROM drops WHERE (status='SCHEDULED' AND preview_at<=clock_timestamp()) OR (status='PREVIEW' AND release_at<=clock_timestamp()) OR (status='LIVE' AND archive_at IS NOT NULL AND archive_at<=clock_timestamp()) ORDER BY updated_at,id`)).rows;if(!rows.length)break;for(const r of rows){const target=r.status==='SCHEDULED'?'PREVIEW':r.status==='PREVIEW'?'LIVE':'ARCHIVED';try{await transitionInternal(null,r.id,target,{});changed++;if(target==='PREVIEW')previewed++;if(target==='LIVE')released++;if(target==='ARCHIVED')archived++}catch(e){if(!['DROP_TRANSITION_INVALID','DROP_PREVIEW_NOT_DUE','DROP_RELEASE_NOT_DUE'].includes(e?.code))throw e}}}return{changed,previewed,released,archived}}
