import {db,uid,now} from './runtime-v09.mjs';
import {assertMinorAmount,normalizeCurrency} from './money-v15.mjs';
import {planLifecycleTransition} from './lifecycle-authority-v16.mjs';
import {recordLifecycleTransitionTx} from './lifecycle-events-v16.mjs';

const memory={accounts:new Map(),transactions:new Map(),payouts:new Map(),reconciliations:new Map()};
export function financeCapabilities(){return{ledger:true,doubleEntry:true,payoutHolds:true,reconciliation:true,moneyContract:'MINOR_UNITS_V15',exactlyOnceEffects:true,paymentProvider:process.env.PAYMENT_PROVIDER||'NOT_CONFIGURED',providerConfigured:Boolean(process.env.PAYMENT_PROVIDER&&process.env.PAYMENT_PROVIDER!=='NOT_CONFIGURED')}}
function validateEntries(entries){
 if(!Array.isArray(entries)||entries.length<2)throw Object.assign(new Error('At least two ledger entries required'),{status:400});
 const normalized=entries.map(e=>{const side=String(e.side||'').toUpperCase();if(!['DEBIT','CREDIT'].includes(side))throw Object.assign(new Error('Ledger entry side must be DEBIT or CREDIT'),{status:400,code:'INVALID_LEDGER_SIDE'});return{...e,side,ownerId:e.ownerId||'__platform__',currency:normalizeCurrency(e.currency),amountMinor:assertMinorAmount(e.amountMinor,{allowZero:false,name:'ledger amountMinor'})}});
 const currencies=new Set(normalized.map(x=>x.currency));if(currencies.size!==1)throw Object.assign(new Error('A ledger transaction cannot mix currencies'),{status:400});
 const debit=normalized.filter(x=>x.side==='DEBIT').reduce((s,x)=>s+BigInt(x.amountMinor),0n),credit=normalized.filter(x=>x.side==='CREDIT').reduce((s,x)=>s+BigInt(x.amountMinor),0n);
 if(debit===0n||debit!==credit)throw Object.assign(new Error('Ledger transaction must balance'),{status:400,code:'UNBALANCED_LEDGER'});
 if(debit>BigInt(Number.MAX_SAFE_INTEGER))throw Object.assign(new Error('Ledger transaction amount exceeds safe integer range'),{status:400,code:'MONEY_AMOUNT_TOO_LARGE'});
 return{currency:[...currencies][0],amountMinor:Number(debit),entries:normalized}
}
const entrySignature=entries=>JSON.stringify(entries.map(e=>({ownerType:e.ownerType,ownerId:e.ownerId||'__platform__',currency:normalizeCurrency(e.currency),accountType:e.accountType,name:e.name,side:e.side,amountMinor:assertMinorAmount(e.amountMinor,{allowZero:false})})).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))));
const idemConflict=message=>Object.assign(new Error(message),{status:409,code:'IDEMPOTENCY_CONFLICT'});
async function ensureLedgerAccountMemory(e){const key=[e.ownerType,e.ownerId,e.currency,e.name].join('|');if(!memory.accounts.has(key))memory.accounts.set(key,{id:uid('lac'),ownerType:e.ownerType,ownerId:e.ownerId,currency:e.currency,accountType:e.accountType,name:e.name,status:'ACTIVE',createdAt:now()});return memory.accounts.get(key)}
async function ensureLedgerAccountTx(cx,e){const r=(await cx.query('INSERT INTO ledger_accounts(id,owner_type,owner_id,currency,account_type,name) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(owner_type,owner_id,currency,name) DO UPDATE SET status=ledger_accounts.status RETURNING *',[uid('lac'),e.ownerType,e.ownerId,e.currency,e.accountType,e.name])).rows[0];return{id:r.id,ownerType:r.owner_type,ownerId:r.owner_id,currency:r.currency,accountType:r.account_type,name:r.name,status:r.status}}
async function loadLedgerByIdempotency(cx,key){const r=(await cx.query('SELECT * FROM ledger_transactions WHERE idempotency_key=$1',[key])).rows[0];if(!r)return null;const entries=(await cx.query(`SELECT la.owner_type AS "ownerType",la.owner_id AS "ownerId",la.currency,la.account_type AS "accountType",la.name,le.side,le.amount_minor AS "amountMinor" FROM ledger_entries le JOIN ledger_accounts la ON la.id=le.ledger_account_id WHERE le.transaction_id=$1 ORDER BY le.id`,[r.id])).rows.map(e=>({...e,amountMinor:assertMinorAmount(e.amountMinor,{allowZero:false})}));const debit=entries.filter(e=>e.side==='DEBIT').reduce((s,e)=>s+e.amountMinor,0);return{id:r.id,transactionType:r.transaction_type,orderId:r.order_id,externalReference:r.external_reference,status:r.status,metadata:r.metadata||{},createdAt:r.created_at?.toISOString?.()||r.created_at,idempotencyKey:r.idempotency_key,currency:entries[0]?.currency||null,amountMinor:debit,entries}}
function assertSameLedgerEffect(existing,check,{transactionType,orderId}){if(existing.transactionType!==transactionType||String(existing.orderId||'')!==String(orderId||'')||existing.currency!==check.currency||existing.amountMinor!==check.amountMinor||entrySignature(existing.entries)!==entrySignature(check.entries))throw idemConflict('Idempotency key already belongs to a different ledger effect')}
export async function postLedgerTransaction({transactionType,orderId=null,externalReference=null,idempotencyKey=null,entries,metadata={}}){
 const check=validateEntries(entries),key=String(idempotencyKey||((externalReference!=null&&String(externalReference)!=='')?`ledger:${transactionType}:${String(metadata?.provider||'')}:${String(externalReference)}`:'')||'')||null,id=uid('ltx');
 if(db.kind!=='POSTGRES'){
  if(key){const prior=[...memory.transactions.values()].find(x=>x.idempotencyKey===key);if(prior){assertSameLedgerEffect(prior,check,{transactionType,orderId});return{...structuredClone(prior),idempotent:true}}}
  const resolved=[];for(const e of check.entries)resolved.push({...e,ledgerAccountId:(await ensureLedgerAccountMemory(e)).id});const tx={id,transactionType,orderId,externalReference,idempotencyKey:key,status:'POSTED',entries:resolved,metadata,createdAt:now(),currency:check.currency,amountMinor:check.amountMinor,idempotent:false};memory.transactions.set(id,tx);return structuredClone(tx)
 }
 const cx=await db.pool.connect();try{
  await cx.query('BEGIN');
  const row=(await cx.query(`INSERT INTO ledger_transactions(id,transaction_type,external_reference,order_id,status,metadata,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING RETURNING id`,[id,transactionType,externalReference,orderId,'POSTED',metadata,key])).rows[0];
  if(!row){if(!key)throw idemConflict('Ledger transaction conflicted without an idempotency key');const existing=await loadLedgerByIdempotency(cx,key);if(!existing)throw idemConflict('Ledger idempotency conflict could not be resolved');assertSameLedgerEffect(existing,check,{transactionType,orderId});await cx.query('COMMIT');return{...existing,idempotent:true}}
  for(const e of check.entries){const a=await ensureLedgerAccountTx(cx,e);await cx.query('INSERT INTO ledger_entries(transaction_id,ledger_account_id,side,amount_minor) VALUES($1,$2,$3,$4)',[id,a.id,e.side,e.amountMinor])}
  await cx.query('COMMIT');return{id,transactionType,orderId,externalReference,idempotencyKey:key,status:'POSTED',metadata,createdAt:now(),currency:check.currency,amountMinor:check.amountMinor,entries:check.entries,idempotent:false}
 }catch(e){try{await cx.query('ROLLBACK')}catch{}throw e}finally{cx.release()}
}
function samePayoutEffect(p,{orderId,sellerId,amountMinor,currency,reason,sourceType,sourceId}){return String(p.orderId||'')===String(orderId||'')&&p.sellerId===sellerId&&p.amountMinor===amountMinor&&p.currency===currency&&p.holdReason===reason&&String(p.sourceType||'')===String(sourceType||'')&&String(p.sourceId||'')===String(sourceId||'')}
function mapPayout(r){return r?{id:r.id,orderId:r.order_id??r.orderId,sellerId:r.seller_id??r.sellerId,provider:r.provider||null,providerReference:r.provider_reference??r.providerReference??null,amountMinor:assertMinorAmount(r.amount_minor??r.amountMinor,{name:'payout amountMinor'}),currency:normalizeCurrency(r.currency),status:r.status,holdReason:r.hold_reason??r.holdReason??null,sourceType:r.source_type??r.sourceType??null,sourceId:r.source_id??r.sourceId??null,idempotencyKey:r.idempotency_key??r.idempotencyKey??null,createdAt:r.created_at?.toISOString?.()||r.createdAt,updatedAt:r.updated_at?.toISOString?.()||r.updatedAt}:null}
export async function createPayoutHold({orderId=null,sellerId,amountMinor,currency,reason='TRUST_AND_DELIVERY_HOLD',sourceType=null,sourceId=null,idempotencyKey=null}){
 const normalizedCurrency=normalizeCurrency(currency),normalizedAmount=assertMinorAmount(amountMinor,{allowZero:false,name:'payout amountMinor'});sourceType=String(sourceType||(orderId?'ORDER':'')||'').toUpperCase()||null;sourceId=String(sourceId||orderId||'')||null;const key=String(idempotencyKey||(sourceType&&sourceId?`payout:${sourceType}:${sourceId}:${reason}`:'')||'')||null,input={orderId,sellerId,amountMinor:normalizedAmount,currency:normalizedCurrency,reason,sourceType,sourceId};
 if(db.kind!=='POSTGRES'){
  const prior=[...memory.payouts.values()].find(x=>(key&&x.idempotencyKey===key)||(sourceType&&sourceId&&x.sourceType===sourceType&&x.sourceId===sourceId&&x.holdReason===reason));if(prior){const mapped=mapPayout(prior);if(!samePayoutEffect(mapped,input))throw idemConflict('Payout idempotency key already belongs to a different effect');return{...mapped,idempotent:true}}
  const p={id:uid('payout'),orderId,sellerId,amountMinor:normalizedAmount,currency:normalizedCurrency,status:'ON_HOLD',holdReason:reason,sourceType,sourceId,idempotencyKey:key,provider:null,providerReference:null,createdAt:now(),updatedAt:now()};memory.payouts.set(p.id,p);return{...mapPayout(p),idempotent:false}
 }
 const p={id:uid('payout'),orderId,sellerId,amountMinor:normalizedAmount,currency:normalizedCurrency,status:'ON_HOLD',holdReason:reason,sourceType,sourceId,idempotencyKey:key,createdAt:now()};const inserted=(await db.pool.query(`INSERT INTO payouts(id,order_id,seller_id,amount_minor,currency,status,hold_reason,source_type,source_id,idempotency_key,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11) ON CONFLICT DO NOTHING RETURNING *`,[p.id,p.orderId,p.sellerId,p.amountMinor,p.currency,p.status,p.holdReason,p.sourceType,p.sourceId,p.idempotencyKey,p.createdAt])).rows[0];if(inserted)return{...mapPayout(inserted),idempotent:false};let existing=null;if(key)existing=(await db.pool.query('SELECT * FROM payouts WHERE idempotency_key=$1',[key])).rows[0];if(!existing&&sourceType&&sourceId)existing=(await db.pool.query('SELECT * FROM payouts WHERE source_type=$1 AND source_id=$2 AND hold_reason=$3',[sourceType,sourceId,reason])).rows[0];if(!existing)throw idemConflict('Payout idempotency conflict could not be resolved');const mapped=mapPayout(existing);if(!samePayoutEffect(mapped,input))throw idemConflict('Payout idempotency key already belongs to a different effect');return{...mapped,idempotent:true}
}
export async function getPayout(id){if(db.kind==='POSTGRES')return mapPayout((await db.pool.query('SELECT * FROM payouts WHERE id=$1',[id])).rows[0]);return mapPayout(memory.payouts.get(id)||null)}
export async function listPayouts({sellerId=null,orderId=null}={}){if(db.kind==='POSTGRES'){const clauses=[],args=[];if(sellerId){args.push(sellerId);clauses.push(`seller_id=$${args.length}`)}if(orderId){args.push(orderId);clauses.push(`order_id=$${args.length}`)}const q=`SELECT * FROM payouts${clauses.length?' WHERE '+clauses.join(' AND '):''} ORDER BY updated_at DESC`;return(await db.pool.query(q,args)).rows.map(mapPayout)}return[...memory.payouts.values()].filter(x=>(!sellerId||x.sellerId===sellerId)&&(!orderId||x.orderId===orderId)).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).map(mapPayout)}
export async function transitionPayout(id,next,{provider=null,providerReference=null,lifecycleAuthority=null,lifecycleFacts={},sourceKey=null}={}){
 next=String(next||'').toUpperCase();const authority=String(lifecycleAuthority||(provider?'PROVIDER':'SYSTEM')).toUpperCase(),facts={...lifecycleFacts,PROVIDER_EVENT_OR_PREVIEW:Boolean(lifecycleFacts.PROVIDER_EVENT_OR_PREVIEW??(provider||process.env.PREVIEW_MODE!=='false'))};
 if(db.kind==='POSTGRES'){
  const cx=await db.pool.connect();try{await cx.query('BEGIN');const row=(await cx.query('SELECT * FROM payouts WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)throw Object.assign(new Error('Payout not found'),{status:404});const p=mapPayout(row),plan=planLifecycleTransition({domain:'PAYOUT',from:p.status,to:next,authority,facts}),nextProvider=provider??p.provider,nextReference=providerReference??p.providerReference,updated=(await cx.query('UPDATE payouts SET status=$2,provider=$3,provider_reference=$4,updated_at=now() WHERE id=$1 RETURNING *',[id,plan.to,nextProvider,nextReference])).rows[0];await recordLifecycleTransitionTx(cx,{plan,aggregateId:id,sourceKey,metadata:{provider:nextProvider,providerReference:nextReference}});await cx.query('COMMIT');return mapPayout(updated)}catch(e){try{await cx.query('ROLLBACK')}catch{}throw e}finally{cx.release()}
 }
 const p=await getPayout(id);if(!p)throw Object.assign(new Error('Payout not found'),{status:404});const plan=planLifecycleTransition({domain:'PAYOUT',from:p.status,to:next,authority,facts}),updated={...p,status:plan.to,provider:provider??p.provider,providerReference:providerReference??p.providerReference,updatedAt:now()};memory.payouts.set(id,updated);return mapPayout(updated)
}
export async function reconciliationSnapshot(){if(db.kind==='POSTGRES'){const [t,p]=await Promise.all([db.pool.query('SELECT status,count(*)::int AS count FROM ledger_transactions GROUP BY status'),db.pool.query('SELECT status,count(*)::int AS count FROM payouts GROUP BY status')]);return{ledger:Object.fromEntries(t.rows.map(x=>[x.status,x.count])),payouts:Object.fromEntries(p.rows.map(x=>[x.status,x.count])),provider:process.env.PAYMENT_PROVIDER||'NOT_CONFIGURED'}}return{ledger:{POSTED:memory.transactions.size},payouts:[...memory.payouts.values()].reduce((a,x)=>(a[x.status]=(a[x.status]||0)+1,a),{}),provider:'NOT_CONFIGURED'}}