import {db,uid,now} from './runtime-v09.mjs';

const memory={accounts:new Map(),transactions:new Map(),payouts:new Map(),reconciliations:new Map()};
export function financeCapabilities(){return{ledger:true,doubleEntry:true,payoutHolds:true,reconciliation:true,paymentProvider:process.env.PAYMENT_PROVIDER||'NOT_CONFIGURED',providerConfigured:Boolean(process.env.PAYMENT_PROVIDER&&process.env.PAYMENT_PROVIDER!=='NOT_CONFIGURED')}}
function assertCurrency(c){if(!/^[A-Z]{3}$/.test(String(c||'')))throw Object.assign(new Error('Invalid currency'),{status:400,code:'INVALID_CURRENCY'})}
function validateEntries(entries){if(!Array.isArray(entries)||entries.length<2)throw Object.assign(new Error('At least two ledger entries required'),{status:400});const normalized=entries.map(e=>({...e,ownerId:e.ownerId||'__platform__',amountMinor:Number(e.amountMinor||0)}));const currencies=new Set(normalized.map(x=>x.currency));if(currencies.size!==1)throw Object.assign(new Error('A ledger transaction cannot mix currencies'),{status:400});const debit=normalized.filter(x=>x.side==='DEBIT').reduce((s,x)=>s+x.amountMinor,0),credit=normalized.filter(x=>x.side==='CREDIT').reduce((s,x)=>s+x.amountMinor,0);if(!debit||debit!==credit)throw Object.assign(new Error('Ledger transaction must balance'),{status:400,code:'UNBALANCED_LEDGER'});assertCurrency([...currencies][0]);return{currency:[...currencies][0],amountMinor:debit,entries:normalized}}
async function ensureLedgerAccountMemory(e){const key=[e.ownerType,e.ownerId,e.currency,e.name].join('|');if(!memory.accounts.has(key))memory.accounts.set(key,{id:uid('lac'),ownerType:e.ownerType,ownerId:e.ownerId,currency:e.currency,accountType:e.accountType,name:e.name,status:'ACTIVE',createdAt:now()});return memory.accounts.get(key)}
async function ensureLedgerAccountTx(cx,e){const r=(await cx.query('INSERT INTO ledger_accounts(id,owner_type,owner_id,currency,account_type,name) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(owner_type,owner_id,currency,name) DO UPDATE SET status=ledger_accounts.status RETURNING *',[uid('lac'),e.ownerType,e.ownerId,e.currency,e.accountType,e.name])).rows[0];return{id:r.id,ownerType:r.owner_type,ownerId:r.owner_id,currency:r.currency,accountType:r.account_type,name:r.name,status:r.status}}
export async function postLedgerTransaction({transactionType,orderId=null,externalReference=null,entries,metadata={}}){const check=validateEntries(entries),id=uid('ltx');if(db.kind!=='POSTGRES'){const resolved=[];for(const e of check.entries)resolved.push({...e,ledgerAccountId:(await ensureLedgerAccountMemory(e)).id});const tx={id,transactionType,orderId,externalReference,status:'POSTED',entries:resolved,metadata,createdAt:now(),currency:check.currency,amountMinor:check.amountMinor};memory.transactions.set(id,tx);return tx}const cx=await db.pool.connect();try{await cx.query('BEGIN');await cx.query('INSERT INTO ledger_transactions(id,transaction_type,external_reference,order_id,status,metadata) VALUES($1,$2,$3,$4,$5,$6)',[id,transactionType,externalReference,orderId,'POSTED',metadata]);for(const e of check.entries){const a=await ensureLedgerAccountTx(cx,e);await cx.query('INSERT INTO ledger_entries(transaction_id,ledger_account_id,side,amount_minor) VALUES($1,$2,$3,$4)',[id,a.id,e.side,e.amountMinor])}await cx.query('COMMIT');return{id,transactionType,orderId,externalReference,status:'POSTED',metadata,createdAt:now(),currency:check.currency,amountMinor:check.amountMinor}}catch(e){try{await cx.query('ROLLBACK')}catch{}throw e}finally{cx.release()}}
export async function createPayoutHold({orderId,sellerId,amountMinor,currency,reason='TRUST_AND_DELIVERY_HOLD'}){assertCurrency(currency);const p={id:uid('payout'),orderId,sellerId,amountMinor:Number(amountMinor),currency,status:'ON_HOLD',holdReason:reason,provider:null,providerReference:null,createdAt:now(),updatedAt:now()};if(db.kind==='POSTGRES')await db.pool.query('INSERT INTO payouts(id,order_id,seller_id,amount_minor,currency,status,hold_reason,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8)',[p.id,p.orderId,p.sellerId,p.amountMinor,p.currency,p.status,p.holdReason,p.createdAt]);else memory.payouts.set(p.id,p);return p}
function mapPayout(r){return r?{id:r.id,orderId:r.order_id??r.orderId,sellerId:r.seller_id??r.sellerId,provider:r.provider||null,providerReference:r.provider_reference??r.providerReference??null,amountMinor:Number(r.amount_minor??r.amountMinor),currency:r.currency,status:r.status,holdReason:r.hold_reason??r.holdReason??null,createdAt:r.created_at?.toISOString?.()||r.createdAt,updatedAt:r.updated_at?.toISOString?.()||r.updatedAt}:null}
export async function getPayout(id){if(db.kind==='POSTGRES')return mapPayout((await db.pool.query('SELECT * FROM payouts WHERE id=$1',[id])).rows[0]);return mapPayout(memory.payouts.get(id)||null)}
export async function listPayouts({sellerId=null,orderId=null}={}){if(db.kind==='POSTGRES'){const clauses=[],args=[];if(sellerId){args.push(sellerId);clauses.push(`seller_id=$${args.length}`)}if(orderId){args.push(orderId);clauses.push(`order_id=$${args.length}`)}const q=`SELECT * FROM payouts${clauses.length?' WHERE '+clauses.join(' AND '):''} ORDER BY updated_at DESC`;return(await db.pool.query(q,args)).rows.map(mapPayout)}return[...memory.payouts.values()].filter(x=>(!sellerId||x.sellerId===sellerId)&&(!orderId||x.orderId===orderId)).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).map(mapPayout)}
const payoutTransitions={ON_HOLD:['READY','REVERSED'],READY:['SUBMITTED','REVERSED'],SUBMITTED:['PAID','FAILED'],FAILED:['READY','REVERSED'],PAID:[],REVERSED:[]};
export async function transitionPayout(id,next,{provider=null,providerReference=null}={}){const p=await getPayout(id);if(!p)throw Object.assign(new Error('Payout not found'),{status:404});next=String(next||'').toUpperCase();if(!payoutTransitions[p.status]?.includes(next))throw Object.assign(new Error(`Invalid payout transition ${p.status} -> ${next}`),{status:409});const updated={...p,status:next,provider:provider??p.provider,providerReference:providerReference??p.providerReference,updatedAt:now()};if(db.kind==='POSTGRES')await db.pool.query('UPDATE payouts SET status=$2,provider=$3,provider_reference=$4,updated_at=now() WHERE id=$1',[id,next,updated.provider,updated.providerReference]);else memory.payouts.set(id,updated);return getPayout(id)}
export async function reconciliationSnapshot(){if(db.kind==='POSTGRES'){const [t,p]=await Promise.all([db.pool.query('SELECT status,count(*)::int AS count FROM ledger_transactions GROUP BY status'),db.pool.query('SELECT status,count(*)::int AS count FROM payouts GROUP BY status')]);return{ledger:Object.fromEntries(t.rows.map(x=>[x.status,x.count])),payouts:Object.fromEntries(p.rows.map(x=>[x.status,x.count])),provider:process.env.PAYMENT_PROVIDER||'NOT_CONFIGURED'}}return{ledger:{POSTED:memory.transactions.size},payouts:[...memory.payouts.values()].reduce((a,x)=>(a[x.status]=(a[x.status]||0)+1,a),{}),provider:'NOT_CONFIGURED'}}
