import crypto from 'node:crypto';
import {SALE,BUYER_ID,SELLER_ID,bi,nowIso,sellers,lots,auctions,listings,step} from './data-v07.mjs';
export const offers=new Map();
export const orders=new Map();
export const messages=new Map();
export const clients=new Map();
export const idem=new Map();
const uid=p=>`${p}-${crypto.randomUUID().replaceAll('-','').slice(0,14)}`;
export function safeSeller(id){const s=sellers.get(id);return s?{...s}:null}
export function publicListing(x){return{...x,seller:safeSeller(x.sellerId)}}
export function normal(a){const t=Date.now();a.state=t<Date.parse(a.startsAt)?'SCHEDULED':t>=Date.parse(a.endsAt)?'CLOSED':'LIVE';a.reserveMet=a.currentBid>=a.reservePrice}
export function pubAuction(a){normal(a);return{id:a.id,saleId:a.saleId,lotId:a.lotId,currency:a.currency,currentBid:a.currentBid,increment:a.increment,bidCount:a.bidCount,reserveMet:a.reserveMet,startsAt:a.startsAt,endsAt:a.endsAt,state:a.state,history:a.history.slice(-12)}}
export function recompute(a){const ranked=[...a.proxyBids].sort((x,y)=>y.maxAmount-x.maxAmount||x.placedAt.localeCompare(y.placedAt));if(!ranked.length)return;const first=ranked[0],second=ranked[1],floor=a.baselineBid+step(a.baselineBid);a.currentBid=Math.max(a.baselineBid,second?Math.max(floor,Math.min(first.maxAmount,second.maxAmount+step(second.maxAmount))):Math.min(first.maxAmount,floor));a.increment=step(a.currentBid);a.leaderClientId=first.clientId}
function baseClient(id){const seller=id===SELLER_ID;return{id,name:seller?'Preview Dealer':'Preview Collector',email:seller?'dealer@preview.antiqua':'collector@preview.antiqua',kind:seller?'SELLER':'BUYER',sellerId:seller?'seller-preview':null,registeredSales:new Set(),acceptedTermsAt:null,country:null,bids:[],watchAlerts:new Set(),savedLots:new Set(),collection:new Set(),notifications:[],createdAt:nowIso()}}
export function getClient(id){if(!clients.has(id))clients.set(id,baseClient(id));return clients.get(id)}
export function client(req){const id=String(req.headers['x-preview-client']||'').trim()||BUYER_ID;return getClient(id)}
export function notify(clientId,type,payload){const c=clients.get(clientId);if(c)c.notifications.unshift({id:uid('ntf'),type,payload,createdAt:nowIso(),read:false})}
function offerForClient(o,c){return o.buyerClientId===c.id||(c.sellerId&&o.sellerId===c.sellerId)}
function orderForClient(o,c){return o.buyerClientId===c.id||(c.sellerId&&o.sellerId===c.sellerId)}
export function clientState(c){return{id:c.id,name:c.name,email:c.email,kind:c.kind,sellerId:c.sellerId,registeredSales:[...c.registeredSales],acceptedTermsAt:c.acceptedTermsAt,country:c.country,leadingLots:auctions.filter(a=>a.leaderClientId===c.id&&a.state==='LIVE').map(a=>a.lotId),bids:c.bids.slice(-30),watchAlerts:[...c.watchAlerts],savedLots:[...c.savedLots],collection:[...c.collection],offers:[...offers.values()].filter(o=>offerForClient(o,c)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),orders:[...orders.values()].filter(o=>orderForClient(o,c)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),notifications:c.notifications.slice(0,30),seller:c.sellerId?{profile:safeSeller(c.sellerId),listings:[...listings.values()].filter(l=>l.sellerId===c.sellerId),pendingOffers:[...offers.values()].filter(o=>o.sellerId===c.sellerId&&['PENDING','COUNTERED_BY_BUYER'].includes(o.status)),inquiries:[...messages.values()].filter(m=>m.sellerId===c.sellerId)}:null}}
export function createOrder({listing,buyerClientId,price,source,offerId=null}){if(listing.status!=='ACTIVE')throw Object.assign(new Error('Item is no longer available'),{status:409});listing.status='RESERVED';const order={id:uid('ord'),listingId:listing.id,lotId:listing.lotId,sellerId:listing.sellerId,buyerClientId,price,currency:listing.currency,source,offerId,status:'AWAITING_PAYMENT_CONNECTOR',paymentStatus:'NOT_CONFIGURED',shippingStatus:'QUOTE_REQUIRED',taxStatus:'NOT_CALCULATED',createdAt:nowIso()};orders.set(order.id,order);notify(buyerClientId,'ORDER_CREATED',{orderId:order.id,lotId:order.lotId});return order}
export function makeOffer(c,listing,amount){if(c.kind!=='BUYER')throw Object.assign(new Error('Switch to buyer cabinet to make an offer'),{status:403});if(!listing||listing.status!=='ACTIVE')throw Object.assign(new Error('Item is not available'),{status:409});if(!listing.negotiable)throw Object.assign(new Error('Seller is not accepting offers on this item'),{status:409});if(!Number.isFinite(amount)||amount<=0||amount>=listing.price)throw Object.assign(new Error('Offer must be positive and below asking price'),{status:400});const offer={id:uid('off'),listingId:listing.id,lotId:listing.lotId,sellerId:listing.sellerId,buyerClientId:c.id,currency:listing.currency,askingPrice:listing.price,buyerAmount:Math.round(amount),sellerAmount:null,status:'PENDING',createdAt:nowIso(),updatedAt:nowIso(),expiresAt:new Date(Date.now()+72*3600000).toISOString(),history:[{by:'BUYER',amount:Math.round(amount),time:nowIso()}]};offers.set(offer.id,offer);notify(c.id,'OFFER_SENT',{offerId:offer.id,lotId:offer.lotId});return offer}
export function respondOffer(c,o,listing,action,amount){if(!o)throw Object.assign(new Error('Offer not found'),{status:404});if(!listing||listing.status!=='ACTIVE')throw Object.assign(new Error('Listing is no longer available'),{status:409});const isSeller=c.sellerId&&c.sellerId===o.sellerId,isBuyer=c.id===o.buyerClientId;if(action==='DECLINE'&&isSeller){o.status='DECLINED';o.updatedAt=nowIso();o.history.push({by:'SELLER',action:'DECLINE',time:nowIso()});notify(o.buyerClientId,'OFFER_DECLINED',{offerId:o.id});return{offer:o}}
if(action==='COUNTER'&&isSeller){const n=Math.round(Number(amount));if(!Number.isFinite(n)||n<=o.buyerAmount||n>listing.price)throw Object.assign(new Error('Counteroffer must be above buyer offer and not above asking price'),{status:400});o.sellerAmount=n;o.status='COUNTERED_BY_SELLER';o.updatedAt=nowIso();o.history.push({by:'SELLER',amount:n,time:nowIso()});notify(o.buyerClientId,'OFFER_COUNTERED',{offerId:o.id,amount:n});return{offer:o}}
if(action==='COUNTER'&&isBuyer){const n=Math.round(Number(amount)),ceiling=o.sellerAmount??listing.price;if(!Number.isFinite(n)||n<=o.buyerAmount||n>=ceiling)throw Object.assign(new Error('Counteroffer must exceed your prior offer and remain below seller amount'),{status:400});o.buyerAmount=n;o.status='COUNTERED_BY_BUYER';o.updatedAt=nowIso();o.history.push({by:'BUYER',amount:n,time:nowIso()});return{offer:o}}
if(action==='ACCEPT'&&isSeller){o.status='ACCEPTED';o.updatedAt=nowIso();const order=createOrder({listing,buyerClientId:o.buyerClientId,price:o.buyerAmount,source:'OFFER',offerId:o.id});notify(o.buyerClientId,'OFFER_ACCEPTED',{offerId:o.id,orderId:order.id});return{offer:o,order}}
if(action==='ACCEPT'&&isBuyer&&o.status==='COUNTERED_BY_SELLER'){o.status='ACCEPTED';o.updatedAt=nowIso();const order=createOrder({listing,buyerClientId:o.buyerClientId,price:o.sellerAmount,source:'COUNTEROFFER',offerId:o.id});return{offer:o,order}}
throw Object.assign(new Error('Action not permitted for this account'),{status:403})}
export function createSellerListing(c,b){if(!c.sellerId)throw Object.assign(new Error('Seller account required'),{status:403});if(!b.titleEn||!b.titleRu||!b.categoryEn||!b.categoryRu)throw Object.assign(new Error('Bilingual title and category are required'),{status:400});const lotNumber=Math.max(...lots.map(l=>l.lotNumber))+1;const lot={id:`lot-${lotNumber}`,lotNumber,department:bi(String(b.categoryEn),String(b.categoryRu)),maker:bi(String(b.makerEn||'Attributed maker'),String(b.makerRu||'Атрибутируемый мастер')),title:bi(String(b.titleEn),String(b.titleRu)),period:bi(String(b.periodEn||''),String(b.periodRu||'')),origin:bi(String(b.originEn||''),String(b.originRu||'')),currency:'EUR',estimateLow:Number(b.estimateLow)||0,estimateHigh:Number(b.estimateHigh)||0,image:String(b.image||'https://images.metmuseum.org/CRDImages/es/web-large/DP340468.jpg'),cataloguing:bi(String(b.descriptionEn||'Seller supplied draft'),String(b.descriptionRu||'Черновик продавца')),provenance:bi([String(b.provenanceEn||'Seller supplied')],[String(b.provenanceRu||'Со слов продавца')]),condition:bi(String(b.conditionEn||'Condition review pending'),String(b.conditionRu||'Проверка состояния ожидается')),literature:bi([],[])};lots.push(lot);const listing={id:uid('lst'),lotId:lot.id,sellerId:c.sellerId,saleType:['BUY_NOW','MAKE_OFFER'].includes(b.saleType)?b.saleType:'BUY_NOW',price:Math.round(Number(b.price)||0),currency:'EUR',negotiable:b.negotiable!==false,status:'DRAFT_REVIEW',shippingFrom:String(b.shippingFrom||'Amsterdam'),createdAt:nowIso()};listings.set(listing.id,listing);return{listing,lot}}
export {SALE,BUYER_ID,SELLER_ID,sellers,lots,auctions,listings,step,bi,nowIso,uid};
