import crypto from 'node:crypto';
const uid=()=>`own-${crypto.randomUUID().replaceAll('-','').slice(0,18)}`;
export async function recordOwnershipTransfer(db,{objectId,newOwnerAccountId,sourceType='OTHER',sourceId=null,eventType='TRANSFERRED',publicNote={}}){
 const occurredAt=new Date().toISOString();
 if(db.kind!=='POSTGRES')return{objectId,newOwnerAccountId,sourceType,sourceId,eventType,occurredAt,persistent:false};
 const c=await db.pool.connect();try{await c.query('BEGIN');const prev=(await c.query('SELECT owner_account_id FROM object_ownership WHERE object_id=$1 FOR UPDATE',[objectId])).rows[0]?.owner_account_id||null;if(prev===newOwnerAccountId){await c.query('COMMIT');return{objectId,newOwnerAccountId,sourceType,sourceId,eventType,occurredAt,idempotent:true,persistent:true}}await c.query(`INSERT INTO object_ownership(object_id,owner_account_id,acquired_at,source_type,source_id,updated_at) VALUES($1,$2,$3,$4,$5,$3) ON CONFLICT(object_id) DO UPDATE SET owner_account_id=excluded.owner_account_id,acquired_at=excluded.acquired_at,source_type=excluded.source_type,source_id=excluded.source_id,updated_at=excluded.updated_at`,[objectId,newOwnerAccountId,occurredAt,sourceType,sourceId]);const id=uid();await c.query('INSERT INTO ownership_events(id,object_id,previous_owner_account_id,new_owner_account_id,event_type,source_type,source_id,public_note,occurred_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9)',[id,objectId,prev,newOwnerAccountId,eventType,sourceType,sourceId,publicNote,occurredAt]);await c.query('COMMIT');return{id,objectId,previousOwnerAccountId:prev,newOwnerAccountId,sourceType,sourceId,eventType,occurredAt,idempotent:false,persistent:true}}catch(e){try{await c.query('ROLLBACK')}catch{}throw e}finally{c.release()}
}
export async function currentOwnership(db,objectId,requesterAccountId=null){if(db.kind!=='POSTGRES')return null;const r=(await db.pool.query('SELECT object_id,owner_account_id,acquired_at,source_type,source_id,updated_at FROM object_ownership WHERE object_id=$1',[objectId])).rows[0];if(!r)return null;return{objectId:r.object_id,ownerAccountId:requesterAccountId===r.owner_account_id?r.owner_account_id:null,isRequesterOwner:requesterAccountId===r.owner_account_id,acquiredAt:r.acquired_at.toISOString(),sourceType:r.source_type,sourceId:requesterAccountId===r.owner_account_id?r.source_id:null,updatedAt:r.updated_at.toISOString()}}
export async function publicOwnershipHistory(db,objectId){if(db.kind!=='POSTGRES')return[];return(await db.pool.query('SELECT event_type,source_type,public_note,occurred_at FROM ownership_events WHERE object_id=$1 ORDER BY occurred_at',[objectId])).rows.map(r=>({eventType:r.event_type,sourceType:r.source_type,publicNote:r.public_note||{},occurredAt:r.occurred_at.toISOString()}))}
