import {PREVIEW,db,send,readBody,requireCsrf,requirePermission,audit,notify,orders,listing,lot,storageConfig} from './runtime-v09.mjs';
import {financeCapabilities,postLedgerTransaction,createPayoutHold,getPayout,listPayouts,transitionPayout,reconciliationSnapshot} from './finance-v10.mjs';
import {majorToMinor,assertMinorAmount} from './money-v15.mjs';
import {claimProviderEvent,markProviderEventProcessed,markProviderEventFailed,providerEventCapabilities} from './provider-events-v15.mjs';
import {createSubscription,listSubscriptions,updateSubscription,createConversation,listConversations,getConversation,postMessage,markConversationRead,upsertCollectionRecord,listCollectionRecords,addMovement,addInsurancePolicy,createSettlementForAuction,settleDueAuctions,ensureShipment,listDisputes,getDispute,addDisputeEvidence,decideDispute,e2eCapabilities} from './domain-e2e-v14.mjs';
import {getSettlement,listSettlements,transitionSettlement,listShipments,getShipment,quoteShipment,transitionShipment,createDispute,commerceLifecycleCapabilities} from './commerce-lifecycle-v16.mjs';
import {discoverySubscriptionCapabilities} from './discovery-matching-v16.mjs';

const SYSTEM={id:null,roles:['ADMIN'],sellerId:null};
const paymentProvider=()=>process.env.PAYMENT_PROVIDER||'NOT_CONFIGURED';
const webhookSecret=()=>process.env.PROVIDER_WEBHOOK_SECRET||'';
const canOperate=a=>Boolean(a?.roles?.includes('ADMIN')||a?.roles?.includes('TRUST_REVIEWER'));
const requireOperator=a=>{if(!canOperate(a))throw Object.assign(new Error('Operator permission required'),{status:403,code:'FORBIDDEN'})};
const participantOrder=(a,o)=>Boolean(o&&(o.buyerClientId===a.id||o.sellerId===a.sellerId||canOperate(a)));

async function loadOrder(id){let o=orders.get(id);if(!o&&db.kind==='POSTGRES'){const r=(await db.pool.query('SELECT payload FROM orders WHERE id=$1',[id])).rows[0];o=r?.payload||null;if(o)orders.set(id,o)}return o}
async function persistOrder(o){orders.set(o.id,o);await db.putOrder(o);return o}
function paymentEntries({sellerId,amountMinor,currency,provider}){return[
 {ownerType:'PAYMENT_PROVIDER',ownerId:provider,currency,accountType:'ASSET',name:'CLEARING',side:'DEBIT',amountMinor},
 {ownerType:'SELLER',ownerId:sellerId||'platform-consignment',currency,accountType:'LIABILITY',name:'SELLER_PAYABLE_HOLD',side:'CREDIT',amountMinor}
]}
function refundEntries({sellerId,amountMinor,currency,provider}){return[
 {ownerType:'SELLER',ownerId:sellerId||'platform-consignment',currency,accountType:'LIABILITY',name:'SELLER_PAYABLE_HOLD',side:'DEBIT',amountMinor},
 {ownerType:'PAYMENT_PROVIDER',ownerId:provider,currency,accountType:'ASSET',name:'CLEARING',side:'CREDIT',amountMinor}
]}
async function captureOrder(o,{provider,externalReference,actorAccountId=null}){
 if(o.paymentStatus==='PAID')return{order:o,idempotent:true,shipment:await ensureShipment({orderId:o.id})};
 const currency=o.currency||'EUR',amountMinor=majorToMinor(o.price,currency),tx=await postLedgerTransaction({transactionType:'PAYMENT_CAPTURE',orderId:o.id,externalReference,idempotencyKey:`payment:order:${o.id}`,entries:paymentEntries({sellerId:o.sellerId,amountMinor,currency,provider}),metadata:{provider,actorAccountId}}),payout=await createPayoutHold({orderId:o.id,sellerId:o.sellerId||'platform-consignment',amountMinor,currency,sourceType:'ORDER',sourceId:o.id,idempotencyKey:`payout:order:${o.id}`});
 o.paymentStatus='PAID';o.status='PAID';o.finance={...(o.finance||{}),paymentLedgerTransactionId:tx.id,payoutId:payout.id,provider,externalReference};o.timeline=[...(o.timeline||[]),{status:'PAID',at:new Date().toISOString()}];await persistOrder(o);const shipment=await ensureShipment({orderId:o.id});const sa=o.sellerId?await db.findAccountBySellerId(o.sellerId):null;if(sa)await notify(sa.id,'PAYMENT_RECEIVED',{orderId:o.id,objectId:o.lotId,payoutId:payout.id});await notify(o.buyerClientId,'PAYMENT_CONFIRMED',{orderId:o.id,objectId:o.lotId});return{order:o,ledgerTransaction:tx,payout,shipment,idempotent:Boolean(tx.idempotent||payout.idempotent)}
}
async function captureSettlement(s,{provider,externalReference,actor=SYSTEM}){
 if(['PAID','FULFILLMENT','COMPLETED','DISPUTED'].includes(s.status)){return{settlement:s,idempotent:true,shipment:await ensureShipment({settlement:s})}}
 const tx=await postLedgerTransaction({transactionType:'AUCTION_PAYMENT_CAPTURE',externalReference,idempotencyKey:`payment:settlement:${s.id}`,entries:paymentEntries({sellerId:s.sellerId,amountMinor:s.winningAmountMinor,currency:s.currency,provider}),metadata:{settlementId:s.id,provider}}),payout=await createPayoutHold({orderId:null,sellerId:s.sellerId||'platform-consignment',amountMinor:s.winningAmountMinor,currency:s.currency,sourceType:'SETTLEMENT',sourceId:s.id,idempotencyKey:`payout:settlement:${s.id}`});
 let updated;try{updated=await transitionSettlement(actor,s.id,'PAID',{metadata:{paymentLedgerTransactionId:tx.id,payoutId:payout.id,provider,externalReference},sourceKey:externalReference})}catch(e){if(e?.status===409){const latest=await getSettlement(actor,s.id);if(latest&&['PAID','FULFILLMENT','COMPLETED','DISPUTED'].includes(latest.status)){return{settlement:latest,ledgerTransaction:tx,payout,shipment:await ensureShipment({settlement:latest}),idempotent:true}}}throw e}
 const shipment=await ensureShipment({settlement:updated});return{settlement:updated,ledgerTransaction:tx,payout,shipment,idempotent:Boolean(tx.idempotent||payout.idempotent||updated.idempotentTransition)}
}
async function applyPaymentEvent(body){const entityType=String(body.entityType||'').toUpperCase(),entityId=String(body.entityId||''),status=String(body.status||body.eventType||'').toUpperCase(),provider=String(body.provider||paymentProvider()),externalReference=String(body.externalReference||body.externalEventId||'');if(!['CAPTURED','PAID','PAYMENT_CAPTURED'].includes(status))return{applied:false,reason:'EVENT_RECORDED_ONLY'};if(entityType==='ORDER'){const o=await loadOrder(entityId);if(!o)throw Object.assign(new Error('Order not found'),{status:404});return{applied:true,...await captureOrder(o,{provider,externalReference})}}if(entityType==='SETTLEMENT'){const s=await getSettlement(SYSTEM,entityId);if(!s)throw Object.assign(new Error('Settlement not found'),{status:404});return{applied:true,...await captureSettlement(s,{provider,externalReference})}}return{applied:false,reason:'UNSUPPORTED_PAYMENT_ENTITY'}}
async function applyShippingEvent(body){const id=String(body.entityId||''),next=String(body.status||body.eventType||'').toUpperCase();const map={BOOKED:'BOOKED',PACKING:'PACKING',IN_TRANSIT:'IN_TRANSIT',DELIVERED:'DELIVERED',DELIVERY_FAILED:'DELIVERY_FAILED',DAMAGE_REPORTED:'DAMAGE_REPORTED',CANCELLED:'CANCELLED'},target=map[next];if(!target)return{applied:false,reason:'EVENT_RECORDED_ONLY'};return{applied:true,shipment:await transitionShipment(SYSTEM,id,target,{...(body.payload||{}),lifecycleAuthority:'PROVIDER',lifecycleFacts:{PROVIDER_EVENT_OR_PREVIEW:true},providerEvent:true,sourceKey:String(body.externalEventId||'')||null})}}
async function applyVerificationEvent(body){const id=String(body.entityId||''),status=String(body.status||body.eventType||'').toUpperCase();if(!['PENDING','VERIFIED','REJECTED','EXPIRED'].includes(status))return{applied:false,reason:'EVENT_RECORDED_ONLY'};const v=await db.getVerification(id);if(!v)throw Object.assign(new Error('Verification not found'),{status:404});v.status=status;v.provider=String(body.provider||v.provider||'NOT_CONFIGURED');v.providerReference=String(body.providerReference||body.externalReference||v.providerReference||'')||null;v.decisionReason=String(body.reason||v.decisionReason||'');v.decidedAt=['VERIFIED','REJECTED'].includes(status)?new Date().toISOString():v.decidedAt;v.updatedAt=new Date().toISOString();await db.putVerification(v);await notify(v.accountId,'VERIFICATION_UPDATED',{verificationId:v.id,status:v.status});return{applied:true,verification:v}}

export async function routeE2EPublicV14(req,res,url){
 if(url.pathname==='/api/health'&&req.method==='GET'){const finance=financeCapabilities();return send(res,200,{status:'ok',service:'antiqua-preview',version:'0.14.0',uiVersion:'0.14.0',preview:PREVIEW,persistence:await db.health(),objectStorage:storageConfig(),e2e:e2eCapabilities(),commerceLifecycle:commerceLifecycleCapabilities(),payments:{...finance,reconciliation:await reconciliationSnapshot()},providerEvents:providerEventCapabilities(),externalProviders:{identity:process.env.KYC_PROVIDER||'NOT_CONFIGURED',payment:paymentProvider(),shipping:process.env.SHIPPING_PROVIDER||'NOT_CONFIGURED'},time:new Date().toISOString()})}
 if(url.pathname==='/api/providers/events'&&req.method==='POST'){
  const secret=webhookSecret();if(!secret)return send(res,503,{error:'Provider webhook is not configured',code:'PROVIDER_WEBHOOK_NOT_CONFIGURED'});if(String(req.headers['x-provider-secret']||'')!==secret)return send(res,401,{error:'Invalid provider webhook secret'});const body=await readBody(req),providerType=String(body.providerType||'').toUpperCase(),provider=String(body.provider||'NOT_CONFIGURED'),externalEventId=String(body.externalEventId||'');if(!['KYC','KYB','PAYMENT','PAYOUT','SHIPPING'].includes(providerType))return send(res,400,{error:'Invalid provider type'});
  const claim=await claimProviderEvent({providerType,provider,externalEventId,eventType:String(body.eventType||body.status||'EVENT'),entityType:body.entityType||null,entityId:body.entityId||null,payload:body});if(claim.processed)return send(res,200,{idempotent:true,processed:true});if(!claim.claimed)return send(res,202,{idempotent:true,processed:false,processing:true});
  try{let application={applied:false};if(providerType==='PAYMENT')application=await applyPaymentEvent(body);if(providerType==='SHIPPING')application=await applyShippingEvent(body);if(['KYC','KYB'].includes(providerType))application=await applyVerificationEvent(body);await markProviderEventProcessed(provider,externalEventId);return send(res,202,{idempotent:claim.idempotent,recovered:Boolean(claim.recovered),processed:true,application})}catch(e){await markProviderEventFailed(provider,externalEventId,e);throw e}
 }
 return false
}

export async function routeE2EV14(req,res,url,ctx){
 if(!ctx)return false;requireCsrf(req,ctx);const a=ctx.account;
 if(url.pathname==='/api/e2e/capabilities'&&req.method==='GET')return send(res,200,{capabilities:e2eCapabilities(),commerceLifecycle:commerceLifecycleCapabilities(),persistence:await db.health(),storage:storageConfig(),finance:financeCapabilities()});

 if(url.pathname==='/api/discovery/subscriptions/capabilities'&&req.method==='GET')return send(res,200,{capabilities:discoverySubscriptionCapabilities()});
 if(url.pathname==='/api/discovery/subscriptions'&&req.method==='GET')return send(res,200,{subscriptions:await listSubscriptions(a)});
 if(url.pathname==='/api/discovery/subscriptions'&&req.method==='POST'){const x=await createSubscription(a,await readBody(req));await audit(req,a,x.idempotent?'DISCOVERY_SUBSCRIPTION_REUSED':'DISCOVERY_SUBSCRIPTION_CREATED','DISCOVERY_SUBSCRIPTION',x.id);return send(res,x.idempotent?200:201,{subscription:x})}
 const sub=url.pathname.match(/^\/api\/discovery\/subscriptions\/([^/]+)$/);if(sub&&req.method==='PATCH'){const x=await updateSubscription(a,sub[1],await readBody(req));if(!x)return send(res,404,{error:'Subscription not found'});await audit(req,a,'DISCOVERY_SUBSCRIPTION_UPDATED','DISCOVERY_SUBSCRIPTION',x.id);return send(res,200,{subscription:x})}

 if(url.pathname==='/api/conversations'&&req.method==='GET')return send(res,200,{conversations:await listConversations(a)});
 if(url.pathname==='/api/conversations'&&req.method==='POST'){const c=await createConversation(a,await readBody(req));await audit(req,a,'CONVERSATION_OPENED','CONVERSATION',c.id);return send(res,201,{conversation:c})}
 const cv=url.pathname.match(/^\/api\/conversations\/([^/]+)(?:\/(messages|read))?$/);if(cv){if(req.method==='GET'&&!cv[2]){const c=await getConversation(a,cv[1]);return c?send(res,200,{conversation:c}):send(res,404,{error:'Conversation not found'})}if(req.method==='POST'&&cv[2]==='messages'){const x=await postMessage(a,cv[1],await readBody(req));await audit(req,a,x.idempotent?'MESSAGE_REPLAY':'MESSAGE_SENT','CONVERSATION',cv[1]);return send(res,x.idempotent?200:201,x)}if(req.method==='POST'&&cv[2]==='read'){const ok=await markConversationRead(a,cv[1]);return ok?send(res,200,{read:true}):send(res,404,{error:'Conversation not found'})}}

 if(url.pathname==='/api/collection-records'&&req.method==='GET')return send(res,200,{records:await listCollectionRecords(a)});
 const cr=url.pathname.match(/^\/api\/collection-records\/([^/]+)(?:\/(movements|insurance))?$/);if(cr){if(req.method==='PUT'&&!cr[2]){const r=await upsertCollectionRecord(a,cr[1],await readBody(req));await audit(req,a,'COLLECTION_RECORD_UPSERTED','OBJECT',cr[1],null,{recordId:r.id});return send(res,200,{record:r})}if(req.method==='POST'&&cr[2]==='movements'){const m=await addMovement(a,cr[1],await readBody(req));await audit(req,a,'COLLECTION_MOVEMENT_ADDED','OBJECT',cr[1],null,{movementId:m.id});return send(res,201,{movement:m})}if(req.method==='POST'&&cr[2]==='insurance'){const p=await addInsurancePolicy(a,cr[1],await readBody(req));await audit(req,a,'INSURANCE_POLICY_ADDED','OBJECT',cr[1],null,{policyId:p.id});return send(res,201,{policy:p})}}

 if(url.pathname==='/api/settlements'&&req.method==='GET')return send(res,200,{settlements:await listSettlements(a)});
 if(url.pathname==='/api/operator/auctions/settle-due'&&req.method==='POST'){requireOperator(a);const made=await settleDueAuctions();await audit(req,a,'AUCTION_SETTLEMENT_SWEEP','AUCTION',null,null,{created:made.length});return send(res,200,{created:made})}
 const force=url.pathname.match(/^\/api\/operator\/auctions\/([^/]+)\/close-preview$/);if(force&&req.method==='POST'){requireOperator(a);if(!PREVIEW)return send(res,404,{error:'Not found'});const s=await createSettlementForAuction(force[1],{forcePreview:true});await audit(req,a,'AUCTION_PREVIEW_FORCE_CLOSED','AUCTION',force[1],null,{settlementId:s.id});return send(res,201,{settlement:s})}
 const st=url.pathname.match(/^\/api\/settlements\/([^/]+)(?:\/(payment-preview|nonpayment|reoffer))?$/);if(st){if(req.method==='GET'&&!st[2]){const s=await getSettlement(a,st[1]);return s?send(res,200,{settlement:s}):send(res,404,{error:'Settlement not found'})}if(req.method==='POST'&&st[2]==='payment-preview'){if(!PREVIEW)return send(res,404,{error:'Not found'});const s=await getSettlement(a,st[1]);if(!s)return send(res,404,{error:'Settlement not found'});if(s.buyerAccountId!==a.id&&!canOperate(a))return send(res,403,{error:'Buyer or operator only'});const x=await captureSettlement(s,{provider:'INTERNAL_PREVIEW',externalReference:`preview-${s.id}`,actor:a});await audit(req,a,'SETTLEMENT_PAYMENT_PREVIEW','SETTLEMENT',s.id,null,{payoutId:x.payout?.id});return send(res,x.idempotent?200:201,x)}if(req.method==='POST'&&st[2]==='nonpayment'){requireOperator(a);const s=await transitionSettlement(a,st[1],'NONPAYMENT',{reason:String((await readBody(req)).reason||'Payment deadline missed')});await audit(req,a,'SETTLEMENT_NONPAYMENT','SETTLEMENT',st[1]);return send(res,200,{settlement:s})}if(req.method==='POST'&&st[2]==='reoffer'){requireOperator(a);const s=await transitionSettlement(a,st[1],'REOFFERED',{note:'No automatic obligation transferred to another bidder'});await audit(req,a,'SETTLEMENT_REOFFERED','SETTLEMENT',st[1]);return send(res,200,{settlement:s})}}

 const opay=url.pathname.match(/^\/api\/orders\/([^/]+)\/payment-preview$/);if(opay&&req.method==='POST'){if(!PREVIEW)return send(res,404,{error:'Not found'});const o=await loadOrder(opay[1]);if(!o||!participantOrder(a,o))return send(res,404,{error:'Order not found'});if(o.buyerClientId!==a.id&&!canOperate(a))return send(res,403,{error:'Buyer or operator only'});const x=await captureOrder(o,{provider:'INTERNAL_PREVIEW',externalReference:`preview-${o.id}`,actorAccountId:a.id});await audit(req,a,'ORDER_PAYMENT_PREVIEW','ORDER',o.id,null,{payoutId:x.payout?.id});return send(res,x.idempotent?200:201,x)}

 if(url.pathname==='/api/shipments'&&req.method==='GET')return send(res,200,{shipments:await listShipments(a)});
 if(url.pathname==='/api/shipments'&&req.method==='POST'){const b=await readBody(req);let s;if(b.orderId){const o=await loadOrder(String(b.orderId));if(!o||!participantOrder(a,o))return send(res,404,{error:'Order not found'});s=await ensureShipment({orderId:o.id})}else if(b.settlementId){const set=await getSettlement(a,String(b.settlementId));if(!set)return send(res,404,{error:'Settlement not found'});s=await ensureShipment({settlement:set})}else return send(res,400,{error:'orderId or settlementId required'});return send(res,201,{shipment:s})}
 const sh=url.pathname.match(/^\/api\/shipments\/([^/]+)(?:\/(quote|transition|confirm-receipt))?$/);if(sh){if(req.method==='GET'&&!sh[2]){const s=await getShipment(a,sh[1]);return s?send(res,200,{shipment:s}):send(res,404,{error:'Shipment not found'})}if(req.method==='POST'&&sh[2]==='quote'){const s=await quoteShipment(a,sh[1],await readBody(req));await audit(req,a,'SHIPMENT_QUOTED','SHIPMENT',sh[1]);return send(res,200,{shipment:s})}if(req.method==='POST'&&sh[2]==='transition'){const b=await readBody(req),s=await transitionShipment(a,sh[1],b.status,b);await audit(req,a,'SHIPMENT_TRANSITION','SHIPMENT',sh[1],null,{status:s.status});return send(res,200,{shipment:s})}if(req.method==='POST'&&sh[2]==='confirm-receipt'){let s=await getShipment(a,sh[1]);if(!s||s.buyerAccountId!==a.id)return send(res,403,{error:'Buyer only'});if(s.status!=='DELIVERED')return send(res,409,{error:'Shipment must be delivered before receipt confirmation'});const disputes=(await listDisputes(a)).filter(d=>(d.shipmentId===s.id||d.orderId===s.orderId||d.settlementId===s.settlementId)&&!['RESOLVED_BUYER','RESOLVED_SELLER','CLOSED','FULL_REFUND'].includes(d.status));if(disputes.length)return send(res,409,{error:'Open dispute blocks ownership confirmation',disputes:disputes.map(x=>x.id)});const record=await upsertCollectionRecord(a,s.objectId,{status:'OWNED',acquisition:{source:s.settlementId?'AUCTION':'ORDER',orderId:s.orderId||null,settlementId:s.settlementId||null,receivedAt:new Date().toISOString()},storage:{location:'Owner custody'}});await addMovement(a,s.objectId,{movementType:'ACQUIRED',note:'Receipt confirmed through ANTIQUA'});let payoutId=null;if(s.orderId){const o=await loadOrder(s.orderId);if(o){o.status='OWNERSHIP_TRANSFERRED';o.shippingStatus='DELIVERED';o.timeline=[...(o.timeline||[]),{status:'DELIVERED',at:new Date().toISOString()},{status:'OWNERSHIP_TRANSFERRED',at:new Date().toISOString()}];await persistOrder(o);payoutId=o.finance?.payoutId||null}}if(s.settlementId){const set=await getSettlement(a,s.settlementId);if(set){const fulfilled=['PAID'].includes(set.status)?await transitionSettlement(a,set.id,'FULFILLMENT',{shipmentId:s.id,lifecycleAuthority:'SYSTEM',sourceKey:`receipt:${s.id}:fulfillment`}):set;const done=fulfilled.status==='FULFILLMENT'?await transitionSettlement(a,fulfilled.id,'COMPLETED',{receiptConfirmed:true,lifecycleAuthority:'SYSTEM',sourceKey:`receipt:${s.id}:completed`}):fulfilled;payoutId=done.metadata?.payoutId||null}}let payout=null;if(payoutId){const p=await getPayout(payoutId);if(p?.status==='ON_HOLD')payout=await transitionPayout(p.id,'READY')}await audit(req,a,'OWNERSHIP_TRANSFER_CONFIRMED','OBJECT',s.objectId,null,{recordId:record.id,payoutId});return send(res,200,{confirmed:true,record,payout})}}

 if(url.pathname==='/api/disputes'&&req.method==='GET')return send(res,200,{disputes:await listDisputes(a)});
 if(url.pathname==='/api/disputes'&&req.method==='POST'){const d=await createDispute(a,await readBody(req));await audit(req,a,'DISPUTE_OPENED','DISPUTE',d.id);return send(res,201,{dispute:d})}
 const ds=url.pathname.match(/^\/api\/disputes\/([^/]+)(?:\/(evidence|decision))?$/);if(ds){if(req.method==='GET'&&!ds[2]){const d=await getDispute(a,ds[1]);return d?send(res,200,{dispute:d}):send(res,404,{error:'Dispute not found'})}if(req.method==='POST'&&ds[2]==='evidence'){const e=await addDisputeEvidence(a,ds[1],await readBody(req));await audit(req,a,'DISPUTE_EVIDENCE_ADDED','DISPUTE',ds[1],null,{evidenceId:e.id});return send(res,201,{evidence:e})}if(req.method==='POST'&&ds[2]==='decision'){requireOperator(a);const body=await readBody(req),d=await decideDispute(a,ds[1],body);let refund=null;if(['FULL_REFUND','PARTIAL_REFUND'].includes(d.status)){const amountMinor=assertMinorAmount(d.decision?.refundAmountMinor||0,{name:'refundAmountMinor'});if(amountMinor>0){const provider=paymentProvider()==='NOT_CONFIGURED'?'INTERNAL_PREVIEW':paymentProvider(),currency='EUR',tx=await postLedgerTransaction({transactionType:d.status,externalReference:`dispute-${d.id}`,idempotencyKey:`refund:dispute:${d.id}:${d.status}`,entries:refundEntries({sellerId:d.sellerId,amountMinor,currency,provider}),metadata:{disputeId:d.id}});refund={ledgerTransactionId:tx.id,amountMinor,currency,idempotent:Boolean(tx.idempotent)};if(d.orderId){for(const p of await listPayouts({orderId:d.orderId}))if(['ON_HOLD','READY','FAILED'].includes(p.status)){try{await transitionPayout(p.id,'REVERSED')}catch{}}}if(d.settlementId){const set=await getSettlement(a,d.settlementId),pid=set?.metadata?.payoutId;if(pid){const p=await getPayout(pid);if(p&&['ON_HOLD','READY','FAILED'].includes(p.status)){try{await transitionPayout(pid,'REVERSED')}catch{}}}}}}await audit(req,a,'DISPUTE_DECIDED','DISPUTE',d.id,null,{status:d.status,refund});return send(res,200,{dispute:d,refund})}}

 if(url.pathname==='/api/payouts'&&req.method==='GET'){const payouts=await listPayouts({sellerId:a.sellerId||null});if(!a.sellerId&&!canOperate(a))return send(res,200,{payouts:[]});return send(res,200,{payouts:canOperate(a)?await listPayouts():payouts})}
 const po=url.pathname.match(/^\/api\/payouts\/([^/]+)\/(release|provider-state)$/);if(po&&req.method==='POST'){requireOperator(a);const p=await getPayout(po[1]);if(!p)return send(res,404,{error:'Payout not found'});const b=await readBody(req);if(po[2]==='release'){if(p.status!=='ON_HOLD')return send(res,409,{error:'Payout is not on hold'});const next=await transitionPayout(p.id,'READY');await audit(req,a,'PAYOUT_RELEASED','PAYOUT',p.id);return send(res,200,{payout:next})}const status=String(b.status||'').toUpperCase();if(!['SUBMITTED','PAID','FAILED'].includes(status))return send(res,400,{error:'Invalid payout provider state'});const next=await transitionPayout(p.id,status,{provider:String(b.provider||paymentProvider()),providerReference:String(b.providerReference||'')||null});await audit(req,a,'PAYOUT_PROVIDER_STATE','PAYOUT',p.id,null,{status});return send(res,200,{payout:next})}

 const vr=url.pathname.match(/^\/api\/verification\/([^/]+)\/resubmit$/);if(vr&&req.method==='POST'){const v=await db.getVerification(vr[1]);if(!v||v.accountId!==a.id)return send(res,404,{error:'Verification not found'});if(!['REJECTED','EXPIRED','PENDING'].includes(v.status))return send(res,409,{error:'Verification cannot be resubmitted from current state'});v.status='PENDING';v.submittedAt=new Date().toISOString();v.updatedAt=v.submittedAt;v.decisionReason='';await db.putVerification(v);await audit(req,a,'VERIFICATION_RESUBMITTED','VERIFICATION',v.id);return send(res,200,{verification:v})}

 return false
}