import crypto from 'node:crypto';import {SALE,sellers,lots,auctions,listings,draftItems,offers,orders,messages,clients,bi,step} from './data-v08.mjs';import {createPersistence,seedAccounts} from './persistence-v09.mjs';import {uid,newToken,tokenHash,fingerprint,appSecret,csrfFor,requirePermission,generateTotpSecret,totpCode,verifyTotp,encryptSecret,decryptSecret,backupCodes,backupCodeHash,hashPassword,verifyPassword} from './security-v09.mjs';import {objectRiskFlags,draftChecklist,draftRiskFlags,publicationDecision} from './trust-v09.mjs';import {storageConfig,createUploadIntent,verifyUpload,createReadUrl} from './storage-v09.mjs';
export{SALE,sellers,lots,auctions,listings,draftItems,offers,orders,messages,clients,bi,step,uid,requirePermission,generateTotpSecret,totpCode,verifyTotp,encryptSecret,decryptSecret,backupCodes,backupCodeHash,hashPassword,verifyPassword,objectRiskFlags,draftChecklist,draftRiskFlags,publicationDecision,storageConfig,createUploadIntent,verifyUpload,createReadUrl};
export const PREVIEW=process.env.PREVIEW_MODE!=='false';appSecret();export const db=await createPersistence({requireDatabase:!PREVIEW});if(db.kind==='POSTGRES')await db.migrate();if(PREVIEW)await seedAccounts(db);export const reviews=new Map();export const now=()=>new Date().toISOString();
export function send(res,status,data,headers={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':"default-src 'self'; img-src 'self' https: data:; style-src 'self'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'",...headers});res.end(JSON.stringify(data))}
export async function readBody(req){let s='';for await(const c of req){s+=c;if(s.length>1e6)throw Object.assign(new Error('Request too large'),{status:413})}return s?JSON.parse(s):{}}
export const parseCookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return[decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}));
const cookie=(n,v,http=true,max=1209600)=>`${n}=${encodeURIComponent(v)}; Path=/; SameSite=Lax; Max-Age=${max}${http?'; HttpOnly':''}${process.env.NODE_ENV==='production'?'; Secure':''}`;
export async function authContext(req){const raw=parseCookies(req).antiqua_session;if(!raw)return null;const session=await db.getSession(tokenHash(raw));if(!session)return null;await db.touchSession(session.tokenHash);const account=await db.getAccount(session.accountId);return account?.status==='ACTIVE'?{account,session,raw}:null}
export function requireCsrf(req,ctx){if(!ctx||['GET','HEAD','OPTIONS'].includes(req.method))return;const c=parseCookies(req),sent=String(req.headers['x-csrf-token']||'');if(!sent||sent!==c.antiqua_csrf||sent!==csrfFor(ctx.session.id))throw Object.assign(new Error('CSRF validation failed'),{status:403,code:'CSRF_FAILED'})}
export async function issueSession(req,res,a){const raw=newToken(),createdAt=now(),session={id:uid('ses'),accountId:a.id,tokenHash:tokenHash(raw),expiresAt:new Date(Date.now()+14*86400000).toISOString(),lastSeenAt:createdAt,ipHash:fingerprint(req.socket?.remoteAddress),userAgent:String(req.headers['user-agent']||'').slice(0,300),createdAt};await db.putSession(session);const csrf=csrfFor(session.id);res.setHeader('set-cookie',[cookie('antiqua_session',raw,true),cookie('antiqua_csrf',csrf,false)]);return{session,csrf}}
export function clearSessionCookies(res){res.setHeader('set-cookie',[cookie('antiqua_session','',true,0),cookie('antiqua_csrf','',false,0)])}
export const publicAccount=(a,v)=>a?{id:a.id,email:a.email,displayName:a.displayName,accountType:a.accountType,status:a.status,sellerId:a.sellerId,twofaStatus:a.twofaStatus,roles:a.roles,verification:v}:null;export const verification=a=>a?db.verificationFor(a.id,a.accountType==='SELLER'?'KYB':'KYC'):null;
export async function audit(req,a,action,type,id,beforeData=null,afterData=null,metadata={}){await db.audit({actorAccountId:a?.id||null,action,entityType:type,entityId:id,requestId:String(req.headers['x-request-id']||crypto.randomUUID()).slice(0,80),ipHash:fingerprint(req.socket?.remoteAddress),beforeData,afterData,metadata})}
export function clientFor(a){if(!clients.has(a.id))clients.set(a.id,{id:a.id,name:a.displayName,email:a.email,kind:a.accountType==='STAFF'?'STAFF':a.roles.includes('SELLER')?'SELLER':'BUYER',sellerId:a.sellerId||null,registeredSales:new Set(),bids:[],savedLots:new Set(),collection:new Set(),watchAlerts:new Set()});const c=clients.get(a.id);c.name=a.displayName;c.sellerId=a.sellerId||null;return c}
export async function notify(accountId,type,payload){const n={id:uid('ntf'),accountId,type,payload,readAt:null,createdAt:now()};await db.notify(n);return n}
export const lot=id=>lots.find(x=>x.id===id),listing=id=>listings.get(id),seller=id=>sellers.get(id);export const publicListing=x=>({...x,lot:lot(x.lotId),seller:seller(x.sellerId)});
export function publicAuction(a){const t=Date.now();a.state=t<Date.parse(a.startsAt)?'SCHEDULED':t>=Date.parse(a.endsAt)?'CLOSED':'LIVE';a.reserveMet=a.currentBid>=a.reservePrice;return{id:a.id,saleId:a.saleId,lotId:a.lotId,currency:a.currency,currentBid:a.currentBid,increment:a.increment,bidCount:a.bidCount,reserveMet:a.reserveMet,startsAt:a.startsAt,endsAt:a.endsAt,state:a.state,history:a.history.slice(-12)}}
export function recompute(a){const r=[...a.proxyBids].sort((x,y)=>y.maxAmount-x.maxAmount||x.placedAt.localeCompare(y.placedAt));if(!r.length)return;const f=r[0],s=r[1],floor=a.baselineBid+step(a.baselineBid);a.currentBid=Math.max(a.baselineBid,s?Math.max(floor,Math.min(f.maxAmount,s.maxAmount+step(s.maxAmount))):Math.min(f.maxAmount,floor));a.increment=step(a.currentBid);a.leaderClientId=f.clientId}
export function reviewFor(key){return reviews.get(key)||{id:`review-${key}`,draftId:key.startsWith('draft-')?key:null,objectId:key.startsWith('lot-')?key:null,assignedTo:null,catalogueStatus:key.startsWith('lot-')?'APPROVED':draftItems.get(key)?.status||'DRAFT',trustStatus:key.startsWith('lot-')?'CLEARED':'UNREVIEWED',riskFlags:[],requestedChanges:[],decisionNote:null,createdAt:now()}}
export async function saveReview(r){reviews.set(r.draftId||r.objectId,r);await db.putReview(r);return r}
export async function clientState(a){const c=clientFor(a),v=await verification(a),ns=await db.listNotifications(a.id);return{id:c.id,name:c.name,email:c.email,kind:c.kind,sellerId:c.sellerId,roles:a.roles,twofaStatus:a.twofaStatus,verification:v,registeredSales:[...c.registeredSales],bids:c.bids,leadingLots:auctions.filter(x=>x.leaderClientId===a.id&&x.state==='LIVE').map(x=>x.lotId),savedLots:[...c.savedLots],collection:[...c.collection],watchAlerts:[...c.watchAlerts],offers:[...offers.values()].filter(x=>x.buyerClientId===a.id||x.sellerId===a.sellerId),orders:[...orders.values()].filter(x=>x.buyerClientId===a.id||x.sellerId===a.sellerId),notifications:ns,unreadNotifications:ns.filter(x=>!x.readAt).length,seller:a.sellerId?{profile:seller(a.sellerId),listings:[...listings.values()].filter(x=>x.sellerId===a.sellerId).map(publicListing),drafts:[...draftItems.values()].filter(x=>x.sellerId===a.sellerId).map(d=>({...d,checklist:draftChecklist(d)}))}:null}}
async function initDomain(){if(db.kind==='POSTGRES'&&await db.hasDomain()){const h=await db.hydrate();lots.splice(0,lots.length,...h.objects);listings.clear();h.listings.forEach(x=>listings.set(x.id,x));auctions.splice(0,auctions.length,...h.auctions);orders.clear();h.orders.forEach(x=>orders.set(x.id,x));offers.clear();h.offers.forEach(x=>offers.set(x.id,x));draftItems.clear();h.drafts.forEach(x=>draftItems.set(x.id,x));h.reviews.forEach(r=>reviews.set(r.draftId||r.objectId,r));return}if(PREVIEW){for(const l of lots)await db.putObject({...l,sellerId:[...listings.values()].find(x=>x.lotId===l.id)?.sellerId||null,passport:l,trustStatus:'CLEARED',publicationStatus:'PUBLIC'});for(const x of listings.values())await db.putListing(x);for(const a of auctions)await db.putAuction(a);for(const d of draftItems.values())await db.putDraft(d)}else{lots.splice(0);listings.clear();auctions.splice(0);orders.clear();offers.clear();draftItems.clear();sellers.clear()}}
await initDomain();
