import crypto from 'node:crypto';
import {promisify} from 'node:util';
const scryptAsync=promisify(crypto.scrypt),B32='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export const ROLE_PERMISSIONS={BUYER:['catalog.read','collection.manage','auction.register','auction.bid','shop.buy','offer.create'],SELLER:['catalog.read','seller.draft.manage','seller.offer.respond','seller.order.read','seller.analytics.read'],DEALER:['catalog.read','seller.draft.manage','seller.offer.respond','seller.order.read','seller.analytics.read','dealer.profile.manage'],EXPERT:['catalog.read','expert.opinion.write'],CATALOGUER:['catalog.read','catalogue.queue.read','catalogue.review'],TRUST_REVIEWER:['catalog.read','catalogue.queue.read','trust.review','verification.review','audit.read'],ADMIN:['*']};
export const hasPermission=(a,p)=>Boolean(a?.roles?.some(r=>ROLE_PERMISSIONS[r]?.includes('*')||ROLE_PERMISSIONS[r]?.includes(p)));
export function requirePermission(a,p){if(!a)throw Object.assign(new Error('Authentication required'),{status:401,code:'AUTH_REQUIRED'});if(!hasPermission(a,p))throw Object.assign(new Error('Permission denied'),{status:403,code:'FORBIDDEN'});return a;}
export function validatePassword(v){const p=String(v||'');return{ok:p.length>=12&&/[A-Z]/.test(p)&&/[a-z]/.test(p)&&/\d/.test(p)&&/[^A-Za-z0-9]/.test(p),requirements:'At least 12 characters with upper, lower, number and symbol'};}
export async function hashPassword(password){const c=validatePassword(password);if(!c.ok)throw Object.assign(new Error(c.requirements),{status:400,code:'WEAK_PASSWORD'});const salt=crypto.randomBytes(16),key=await scryptAsync(password,salt,64,{N:16384,r:8,p:1});return`scrypt$16384$${salt.toString('base64url')}$${Buffer.from(key).toString('base64url')}`;}
export async function verifyPassword(password,encoded){try{const [kind,n,salt,key]=String(encoded).split('$');if(kind!=='scrypt')return false;const actual=await scryptAsync(String(password),Buffer.from(salt,'base64url'),64,{N:Number(n),r:8,p:1});return crypto.timingSafeEqual(Buffer.from(key,'base64url'),Buffer.from(actual));}catch{return false;}}
export const newToken=()=>crypto.randomBytes(32).toString('base64url');export const tokenHash=t=>crypto.createHash('sha256').update(String(t)).digest('hex');export const fingerprint=v=>crypto.createHash('sha256').update(String(v||'')).digest('hex').slice(0,32);export const uid=p=>`${p}-${crypto.randomUUID().replaceAll('-','').slice(0,18)}`;
export function appSecret(){if(process.env.APP_SECRET)return process.env.APP_SECRET;if(process.env.PREVIEW_MODE==='false')throw new Error('APP_SECRET is required when PREVIEW_MODE=false');return 'antiqua-preview-secret-not-for-production';}
export const csrfFor=sid=>crypto.createHmac('sha256',appSecret()).update(String(sid)).digest('base64url');
const secretKey=()=>crypto.createHash('sha256').update(appSecret()).digest();
export function encryptSecret(text){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',secretKey(),iv),enc=Buffer.concat([c.update(String(text),'utf8'),c.final()]);return`${iv.toString('base64url')}.${c.getAuthTag().toString('base64url')}.${enc.toString('base64url')}`;}
export function decryptSecret(payload){const [iv,tag,enc]=String(payload).split('.'),d=crypto.createDecipheriv('aes-256-gcm',secretKey(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(enc,'base64url')),d.final()]).toString('utf8');}
function b32e(buf){let bits=0,value=0,out='';for(const b of buf){value=(value<<8)|b;bits+=8;while(bits>=5){out+=B32[(value>>>(bits-5))&31];bits-=5}}if(bits)out+=B32[(value<<(5-bits))&31];return out}
function b32d(str){let bits=0,value=0,out=[];for(const ch of String(str).replace(/=+$/,'').toUpperCase()){const i=B32.indexOf(ch);if(i<0)continue;value=(value<<5)|i;bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8}}return Buffer.from(out)}
export const generateTotpSecret=()=>b32e(crypto.randomBytes(20));
export function totpCode(secret,at=Date.now()){const counter=Math.floor(at/30000),msg=Buffer.alloc(8);msg.writeBigUInt64BE(BigInt(counter));const h=crypto.createHmac('sha1',b32d(secret)).update(msg).digest(),o=h[h.length-1]&15,n=(h.readUInt32BE(o)&0x7fffffff)%1e6;return String(n).padStart(6,'0')}
export function verifyTotp(secret,code,at=Date.now()){const c=String(code||'').replace(/\s/g,'');if(!/^\d{6}$/.test(c))return false;return[-1,0,1].some(w=>crypto.timingSafeEqual(Buffer.from(totpCode(secret,at+w*30000)),Buffer.from(c)))}
export const backupCodes=(n=8)=>Array.from({length:n},()=>crypto.randomBytes(5).toString('hex').toUpperCase());export const backupCodeHash=c=>crypto.createHash('sha256').update(String(c||'').replace(/[^A-Za-z0-9]/g,'').toUpperCase()).digest('hex');
