import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {extname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {SALE,BUYER_ID,SELLER_ID,sellers,lots,auctions,listings,draftItems,offers,orders,messages,idem,step,bi} from './data-v08.mjs';
import {ensureClient,clientState,publicAuction,recomputeAuction,publicListing,getLot,getSeller,getListing,checklist,createOrder,orderDetail,notify,uid,nowIso} from './market-v08.mjs';
const PORT=Number(process.env.PORT||10000),ROOT=fileURLToPath(new URL('.',import.meta.url)),PUBLIC=join(ROOT,'public');
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()'});res.end(JSON.stringify(data));};
async function body(req){let raw='';for await(const c of req){raw+=c;if(raw.length>800000)throw Object.assign(new Error('Request too large'),{status:413});}return raw?JSON.parse(raw):{};}
function client(req){return ensureClient(String(req.headers['x-preview-client']||BUYER_ID).trim()||BUYER_ID);}
function requireSeller(c){if(!c.sellerId)throw Object.assign(new Error('Seller account required'),{status:403});return c.sellerId;}
function canSeeOrder(c,o){return o&&(o.buyerClientId===c.id||(c.sellerId&&o.sellerId===c.sellerId));}

async function api(req,res,url){
 try{
  if(url.pathname==='/api/health')return json(res,200,{status:'ok',service:'antiqua-preview',version:'0.8.0',persistence:'ephemeral',time:nowIso()});
  const c=client(req);
  if(url.pathname==='/api/catalog'&&req.method==='GET')return json(res,200,{sale:{id:SALE,title:bi('The Collector: European Decorative Arts','Коллекционер: европейское декоративное искусство'),location:bi('Amsterdam · Online','Амстердам · Онлайн'),status:'LIVE'},lots,auctions:auctions.map(publicAuction),listings:[...listings.values()].filter(l=>l.status==='ACTIVE').map(publicListing),sellers:[...sellers.values()],categories:[...new Set(lots.map(l=>l.department.en))].sort()});
  if(url.pathname==='/api/client-state'&&req.method==='GET')return json(res,200,clientState(c));
  if(url.pathname==='/api/preview/persona'&&req.method==='POST'){const b=await body(req),id=b.persona==='SELLER'?SELLER_ID:BUYER_ID;return json(res,200,{previewClientId:id,client:clientState(ensureClient(id))});}

  const sellerPage=url.pathname.match(/^\/api\/sellers\/([^/]+)$/);if(sellerPage&&req.method==='GET'){const seller=getSeller(sellerPage[1]);if(!seller)return json(res,404,{error:'Seller not found'});const inventory=[...listings.values()].filter(l=>l.sellerId===seller.id&&l.status==='ACTIVE').map(publicListing);return json(res,200,{seller,inventory,stats:{active:inventory.length,sold:[...orders.values()].filter(o=>o.sellerId===seller.id&&o.status!=='CANCELLED').length,totalViews:inventory.reduce((s,x)=>s+(x.views||0),0),totalSaves:inventory.reduce((s,x)=>s+(x.saves||0),0)}});}
  const passport=url.pathname.match(/^\/api\/lots\/([^/]+)\/passport$/);if(passport&&req.method==='GET'){const lot=getLot(passport[1]);if(!lot)return json(res,404,{error:'Lot not found'});const listing=[...listings.values()].find(l=>l.lotId===lot.id&&['ACTIVE','RESERVED'].includes(l.status));const auction=auctions.find(a=>a.lotId===lot.id);return json(res,200,{lot,commercial:{listing:listing?publicListing(listing):null,auction:auction?publicAuction(auction):null},evidenceSummary:{ownerSupplied:lot.documents.filter(d=>d.status==='USER_SUPPLIED').length,platformRecords:lot.provenanceTimeline.filter(x=>x.evidenceStatus==='PLATFORM_RECORD').length,expertOpinions:0},disclaimer:'Catalogue approval is not a guarantee of authenticity.'});}

  if(url.pathname===`/api/sales/${SALE}/register`&&req.method==='POST'){const b=await body(req);if(b.acceptTerms!==true)return json(res,400,{error:'Terms acceptance is required'});c.registeredSales.add(SALE);c.acceptedTermsAt=nowIso();c.country=String(b.country||'').slice(0,80)||null;return json(res,200,{registered:true,clientState:clientState(c),preview:true});}
  const bid=url.pathname.match(/^\/api\/auctions\/([^/]+)\/bid$/);if(bid&&req.method==='POST'){if(c.kind!=='BUYER')return json(res,403,{error:'Seller preview account cannot bid'});const a=auctions.find(x=>x.id===bid[1]);if(!a)return json(res,404,{error:'Auction not found'});publicAuction(a);if(a.state!=='LIVE')return json(res,409,{error:'Auction is not open'});if(!c.registeredSales.has(a.saleId))return json(res,403,{error:'Register for the sale before bidding',code:'REGISTRATION_REQUIRED'});const b=await body(req),max=Math.round(Number(b.maxAmount??b.amount)),min=a.currentBid+step(a.currentBid);if(!Number.isFinite(max)||max<min)return json(res,400,{error:`Minimum maximum bid is ${min}`,minimum:min});const key=String(req.headers['idempotency-key']||'').trim(),scope=`${c.id}:${key}`;if(key&&idem.has(scope))return json(res,200,idem.get(scope));const ex=a.proxyBids.find(x=>x.clientId===c.id);if(ex){if(max<=ex.maxAmount)return json(res,409,{error:'New maximum must exceed existing maximum'});ex.maxAmount=max;ex.placedAt=nowIso();}else a.proxyBids.push({clientId:c.id,maxAmount:max,placedAt:nowIso()});recomputeAuction(a);a.bidCount++;if(Date.parse(a.endsAt)-Date.now()<180000)a.endsAt=new Date(Date.now()+180000).toISOString();a.history.push({amount:a.currentBid,bidder:`Bidder ${a.leaderClientId.slice(-2).toUpperCase()}•••`,time:nowIso(),type:'proxy'});const leading=a.leaderClientId===c.id;c.bids.push({auctionId:a.id,lotId:a.lotId,maxAmount:max,submittedAt:nowIso(),leading,currentPrice:a.currentBid});const out={auction:publicAuction(a),leading,preview:true};if(key)idem.set(scope,out);return json(res,201,out);}
  const hist=url.pathname.match(/^\/api\/auctions\/([^/]+)\/history$/);if(hist&&req.method==='GET'){const a=auctions.find(x=>x.id===hist[1]);return a?json(res,200,{auction:publicAuction(a),history:publicAuction(a).history}):json(res,404,{error:'Auction not found'});}

  const alert=url.pathname.match(/^\/api\/lots\/([^/]+)\/alert$/);if(alert&&req.method==='POST'){const b=await body(req);b.enabled===false?c.watchAlerts.delete(alert[1]):c.watchAlerts.add(alert[1]);return json(res,200,{enabled:c.watchAlerts.has(alert[1]),clientState:clientState(c)});}
  const save=url.pathname.match(/^\/api\/lots\/([^/]+)\/save$/);if(save&&req.method==='POST'){const b=await body(req);b.enabled===false?c.savedLots.delete(save[1]):c.savedLots.add(save[1]);return json(res,200,{enabled:c.savedLots.has(save[1]),clientState:clientState(c)});}
  const collect=url.pathname.match(/^\/api\/lots\/([^/]+)\/collect$/);if(collect&&req.method==='POST'){c.collection.add(collect[1]);return json(res,200,{enabled:true,clientState:clientState(c)});}

  const buy=url.pathname.match(/^\/api\/listings\/([^/]+)\/buy$/);if(buy&&req.method==='POST'){if(c.kind!=='BUYER')return json(res,403,{error:'Switch to buyer cabinet'});const l=getListing(buy[1]);if(!l)return json(res,404,{error:'Listing not found'});const order=createOrder({listing:l,buyerClientId:c.id,price:l.price,source:'BUY_NOW'});return json(res,201,{order:orderDetail(order),preview:true});}
  const offerRoute=url.pathname.match(/^\/api\/listings\/([^/]+)\/offers$/);if(offerRoute&&req.method==='POST'){if(c.kind!=='BUYER')return json(res,403,{error:'Switch to buyer cabinet'});const l=getListing(offerRoute[1]);if(!l||l.status!=='ACTIVE')return json(res,409,{error:'Item is not available'});if(!l.negotiable)return json(res,409,{error:'Seller is not accepting offers'});const b=await body(req),amount=Math.round(Number(b.amount));if(!Number.isFinite(amount)||amount<=0||amount>=l.price)return json(res,400,{error:'Offer must be positive and below asking price'});const o={id:uid('off'),listingId:l.id,lotId:l.lotId,sellerId:l.sellerId,buyerClientId:c.id,currency:l.currency,askingPrice:l.price,buyerAmount:amount,sellerAmount:null,status:'PENDING',createdAt:nowIso(),updatedAt:nowIso(),expiresAt:new Date(Date.now()+72*3600000).toISOString(),history:[{by:'BUYER',amount,time:nowIso()}]};offers.set(o.id,o);notify(c.id,'OFFER_SENT',{offerId:o.id,lotId:o.lotId});notify(SELLER_ID,'NEW_OFFER',{offerId:o.id,lotId:o.lotId});return json(res,201,{offer:o,preview:true});}
  const respond=url.pathname.match(/^\/api\/offers\/([^/]+)\/respond$/);if(respond&&req.method==='POST'){const o=offers.get(respond[1]);if(!o)return json(res,404,{error:'Offer not found'});const l=getListing(o.listingId);if(!l||l.status!=='ACTIVE')return json(res,409,{error:'Listing is no longer available'});const b=await body(req),action=String(b.action||'').toUpperCase(),isSeller=c.sellerId===o.sellerId,isBuyer=c.id===o.buyerClientId;if(action==='DECLINE'&&isSeller){o.status='DECLINED';o.updatedAt=nowIso();notify(o.buyerClientId,'OFFER_DECLINED',{offerId:o.id});return json(res,200,{offer:o});}if(action==='COUNTER'&&isSeller){const amount=Math.round(Number(b.amount));if(!Number.isFinite(amount)||amount<=o.buyerAmount||amount>l.price)return json(res,400,{error:'Invalid counteroffer'});o.sellerAmount=amount;o.status='COUNTERED_BY_SELLER';o.updatedAt=nowIso();o.history.push({by:'SELLER',amount,time:nowIso()});notify(o.buyerClientId,'OFFER_COUNTERED',{offerId:o.id,amount});return json(res,200,{offer:o});}if(action==='ACCEPT'&&isSeller){o.status='ACCEPTED';o.updatedAt=nowIso();const order=createOrder({listing:l,buyerClientId:o.buyerClientId,price:o.buyerAmount,source:'OFFER',offerId:o.id});return json(res,200,{offer:o,order:orderDetail(order)});}if(action==='ACCEPT'&&isBuyer&&o.status==='COUNTERED_BY_SELLER'){o.status='ACCEPTED';o.updatedAt=nowIso();const order=createOrder({listing:l,buyerClientId:o.buyerClientId,price:o.sellerAmount,source:'COUNTEROFFER',offerId:o.id});return json(res,200,{offer:o,order:orderDetail(order)});}return json(res,403,{error:'Action not permitted'});}

  const orderRoute=url.pathname.match(/^\/api\/orders\/([^/]+)$/);if(orderRoute&&req.method==='GET'){const o=orders.get(orderRoute[1]);if(!canSeeOrder(c,o))return json(res,404,{error:'Order not found'});return json(res,200,{order:orderDetail(o)});}
  const quote=url.pathname.match(/^\/api\/orders\/([^/]+)\/shipping-quote$/);if(quote&&req.method==='POST'){const o=orders.get(quote[1]);if(!canSeeOrder(c,o))return json(res,404,{error:'Order not found'});if(c.kind!=='BUYER')return json(res,403,{error:'Buyer action required'});const b=await body(req),country=String(b.country||'Netherlands').slice(0,80);o.shippingQuote={country,amount:o.price>8000?320:180,currency:o.currency,insuranceIncluded:true,provider:'Preview Fine Art Logistics',validUntil:new Date(Date.now()+7*86400000).toISOString()};o.shippingStatus='QUOTE_READY';o.timeline.push({status:'SHIPPING_QUOTE_READY',at:nowIso()});return json(res,200,{order:orderDetail(o),preview:true});}
  const cancel=url.pathname.match(/^\/api\/orders\/([^/]+)\/cancel$/);if(cancel&&req.method==='POST'){const o=orders.get(cancel[1]);if(!o||o.buyerClientId!==c.id)return json(res,404,{error:'Order not found'});if(o.status!=='AWAITING_PAYMENT_CONNECTOR')return json(res,409,{error:'Order cannot be cancelled'});o.status='CANCELLED';o.timeline.push({status:'CANCELLED',at:nowIso()});const l=getListing(o.listingId);if(l&&l.status==='RESERVED')l.status='ACTIVE';return json(res,200,{order:orderDetail(o)});}

  const msg=url.pathname.match(/^\/api\/listings\/([^/]+)\/message$/);if(msg&&req.method==='POST'){const l=getListing(msg[1]);if(!l)return json(res,404,{error:'Listing not found'});const b=await body(req),text=String(b.message||'').trim();if(text.length<4)return json(res,400,{error:'Message is too short'});const m={id:uid('msg'),listingId:l.id,lotId:l.lotId,sellerId:l.sellerId,buyerClientId:c.id,text:text.slice(0,1200),createdAt:nowIso(),status:'OPEN'};messages.set(m.id,m);return json(res,201,{message:m,preview:true});}

  if(url.pathname==='/api/notifications'&&req.method==='GET')return json(res,200,{notifications:c.notifications,unread:c.notifications.filter(n=>!n.read).length});
  const mark=url.pathname.match(/^\/api\/notifications\/([^/]+)\/read$/);if(mark&&req.method==='POST'){const n=c.notifications.find(x=>x.id===mark[1]);if(!n)return json(res,404,{error:'Notification not found'});n.read=true;return json(res,200,{notification:n,unread:c.notifications.filter(x=>!x.read).length});}
  if(url.pathname==='/api/notifications/read-all'&&req.method==='POST'){c.notifications.forEach(n=>n.read=true);return json(res,200,{unread:0});}

  if(url.pathname==='/api/seller/drafts'&&req.method==='POST'){const sellerId=requireSeller(c),b=await body(req);const d={id:uid('draft'),sellerId,status:'DRAFT',saleRoute:['SHOP','AUCTION','PRIVATE'].includes(b.saleRoute)?b.saleRoute:'SHOP',createdAt:nowIso(),updatedAt:nowIso(),title:bi(String(b.titleEn||''),String(b.titleRu||'')),category:bi(String(b.categoryEn||''),String(b.categoryRu||'')),maker:bi(String(b.makerEn||''),String(b.makerRu||'')),period:bi(String(b.periodEn||''),String(b.periodRu||'')),origin:bi(String(b.originEn||''),String(b.originRu||'')),materials:bi(String(b.materialsEn||''),String(b.materialsRu||'')),dimensions:bi(String(b.dimensionsEn||''),String(b.dimensionsRu||'')),description:bi(String(b.descriptionEn||''),String(b.descriptionRu||'')),provenance:bi(String(b.provenanceEn||''),String(b.provenanceRu||'')),condition:bi(String(b.conditionEn||''),String(b.conditionRu||'')),price:Number(b.price)||0,estimateLow:Number(b.estimateLow)||0,estimateHigh:Number(b.estimateHigh)||0,shippingFrom:String(b.shippingFrom||''),media:Array.isArray(b.media)?b.media.slice(0,12):[],documents:[],reviewNotes:[]};draftItems.set(d.id,d);return json(res,201,{draft:{...d,checklist:checklist(d)},preview:true});}
  const draftRoute=url.pathname.match(/^\/api\/seller\/drafts\/([^/]+)$/);if(draftRoute&&req.method==='PATCH'){const sellerId=requireSeller(c),d=draftItems.get(draftRoute[1]);if(!d||d.sellerId!==sellerId)return json(res,404,{error:'Draft not found'});if(['CATALOGUE_REVIEW','APPROVED','PUBLISHED'].includes(d.status))return json(res,409,{error:'Draft is locked during/after review'});const b=await body(req);for(const k of ['price','estimateLow','estimateHigh'])if(k in b)d[k]=Number(b[k])||0;for(const k of ['shippingFrom','saleRoute'])if(k in b)d[k]=String(b[k]);for(const k of ['title','category','maker','period','origin','materials','dimensions','description','provenance','condition'])if(b[k]&&typeof b[k]==='object')d[k]={en:String(b[k].en||''),ru:String(b[k].ru||'')};if(Array.isArray(b.media))d.media=b.media.slice(0,12);d.updatedAt=nowIso();if(d.status==='CHANGES_REQUESTED')d.status='DRAFT';return json(res,200,{draft:{...d,checklist:checklist(d)}});}
  const submit=url.pathname.match(/^\/api\/seller\/drafts\/([^/]+)\/submit$/);if(submit&&req.method==='POST'){const sellerId=requireSeller(c),d=draftItems.get(submit[1]);if(!d||d.sellerId!==sellerId)return json(res,404,{error:'Draft not found'});const cl=checklist(d);if(!cl.ready)return json(res,409,{error:'Publication checklist is incomplete',checklist:cl});d.status='CATALOGUE_REVIEW';d.submittedAt=nowIso();d.updatedAt=nowIso();return json(res,200,{draft:{...d,checklist:cl},preview:true});}

  return json(res,404,{error:'Not found'});
 }catch(e){return json(res,e.status||500,{error:e.message||'Unexpected server error'});}
}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8'};
async function serve(req,res,url){let p=url.pathname==='/'?'/index.html':url.pathname;if(p.includes('..'))return json(res,400,{error:'Invalid path'});try{const d=await readFile(join(PUBLIC,p));res.writeHead(200,{'Content-Type':mime[extname(p)]||'application/octet-stream','Cache-Control':p==='/index.html'?'no-store':'public, max-age=300','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'});res.end(d);}catch{const d=await readFile(join(PUBLIC,'index.html'));res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(d);}}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);return url.pathname.startsWith('/api/')?await api(req,res,url):await serve(req,res,url);}catch(e){console.error(e);json(res,500,{error:'Unexpected server error'});}});
server.listen(PORT,'0.0.0.0',()=>console.log(`ANTIQUA 0.8 preview listening on ${PORT}`));
