import http from 'node:http';
import crypto from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {extname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {SALE,sellers,lots,auctions,listings,offers,orders,messages,idem,client,clientState,publicListing,pubAuction,normal,recompute,createOrder,makeOffer,respondOffer,createSellerListing,step,nowIso} from './market-v07.mjs';
const PORT=Number(process.env.PORT||10000),ROOT=fileURLToPath(new URL('.',import.meta.url)),PUBLIC=join(ROOT,'public');
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()'});res.end(JSON.stringify(data))};
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>500000)throw Object.assign(new Error('Request too large'),{status:413})}return raw?JSON.parse(raw):{}}
async function api(req,res,url){try{
if(url.pathname==='/api/health')return json(res,200,{status:'ok',service:'antiqua-preview',version:'0.7.0',persistence:'ephemeral',time:nowIso()});
const c=client(req);
if(url.pathname==='/api/catalog'&&req.method==='GET')return json(res,200,{sale:{id:SALE,title:{en:'The Collector: European Decorative Arts',ru:'Коллекционер: европейское декоративное искусство'},location:{en:'Amsterdam · Online',ru:'Амстердам · Онлайн'},status:'LIVE'},lots,auctions:auctions.map(pubAuction),listings:[...listings.values()].filter(l=>l.status==='ACTIVE').map(publicListing),sellers:[...sellers.values()]});
if(url.pathname==='/api/client-state'&&req.method==='GET')return json(res,200,clientState(c));
if(url.pathname===`/api/sales/${SALE}/register`&&req.method==='POST'){const b=await body(req);if(b.acceptTerms!==true)return json(res,400,{error:'Terms acceptance is required'});c.registeredSales.add(SALE);c.acceptedTermsAt=nowIso();c.country=String(b.country||'').slice(0,80)||null;return json(res,200,{registered:true,clientState:clientState(c),preview:true})}
const hist=url.pathname.match(/^\/api\/auctions\/([^/]+)\/history$/);if(hist&&req.method==='GET'){const a=auctions.find(x=>x.id===hist[1]);return a?json(res,200,{auction:pubAuction(a),history:pubAuction(a).history}):json(res,404,{error:'Auction not found'})}
const alert=url.pathname.match(/^\/api\/lots\/([^/]+)\/alert$/);if(alert&&req.method==='POST'){const b=await body(req);b.enabled===false?c.watchAlerts.delete(alert[1]):c.watchAlerts.add(alert[1]);return json(res,200,{enabled:c.watchAlerts.has(alert[1]),clientState:clientState(c)})}
const save=url.pathname.match(/^\/api\/lots\/([^/]+)\/save$/);if(save&&req.method==='POST'){const b=await body(req);b.enabled===false?c.savedLots.delete(save[1]):c.savedLots.add(save[1]);return json(res,200,{enabled:c.savedLots.has(save[1]),clientState:clientState(c)})}
const collect=url.pathname.match(/^\/api\/lots\/([^/]+)\/collect$/);if(collect&&req.method==='POST'){c.collection.add(collect[1]);return json(res,200,{enabled:true,clientState:clientState(c)})}
const bid=url.pathname.match(/^\/api\/auctions\/([^/]+)\/bid$/);if(bid&&req.method==='POST'){if(c.kind!=='BUYER')return json(res,403,{error:'Seller preview account cannot bid. Switch to buyer cabinet.'});const a=auctions.find(x=>x.id===bid[1]);if(!a)return json(res,404,{error:'Auction not found'});normal(a);if(a.state!=='LIVE')return json(res,409,{error:'Auction is not open'});if(!c.registeredSales.has(a.saleId))return json(res,403,{error:'Register for the sale before bidding',code:'REGISTRATION_REQUIRED'});const b=await body(req),max=Math.round(Number(b.maxAmount??b.amount)),min=a.currentBid+step(a.currentBid);if(!Number.isFinite(max)||max<min)return json(res,400,{error:`Minimum maximum bid is ${min}`,minimum:min});const key=String(req.headers['idempotency-key']||'').trim(),scope=`${c.id}:${key}`;if(key&&idem.has(scope))return json(res,200,idem.get(scope));const ex=a.proxyBids.find(x=>x.clientId===c.id);if(ex){if(max<=ex.maxAmount)return json(res,409,{error:'New maximum must exceed your existing maximum'});ex.maxAmount=max;ex.placedAt=nowIso()}else a.proxyBids.push({clientId:c.id,maxAmount:max,placedAt:nowIso()});recompute(a);a.bidCount++;a.reserveMet=a.currentBid>=a.reservePrice;if(Date.parse(a.endsAt)-Date.now()<180000)a.endsAt=new Date(Date.now()+180000).toISOString();a.history.push({amount:a.currentBid,bidder:`Bidder ${a.leaderClientId.slice(-2).toUpperCase()}•••`,time:nowIso(),type:'proxy'});const leading=a.leaderClientId===c.id;c.bids.push({auctionId:a.id,lotId:a.lotId,maxAmount:max,submittedAt:nowIso(),leading,currentPrice:a.currentBid});const out={auction:pubAuction(a),leading,preview:true};if(key)idem.set(scope,out);return json(res,201,out)}
const buy=url.pathname.match(/^\/api\/listings\/([^/]+)\/buy$/);if(buy&&req.method==='POST'){if(c.kind!=='BUYER')return json(res,403,{error:'Switch to buyer cabinet to purchase'});const l=listings.get(buy[1]);if(!l)return json(res,404,{error:'Listing not found'});try{return json(res,201,{order:createOrder({listing:l,buyerClientId:c.id,price:l.price,source:'BUY_NOW'}),preview:true})}catch(e){return json(res,e.status||409,{error:e.message})}}
const offerRoute=url.pathname.match(/^\/api\/listings\/([^/]+)\/offers$/);if(offerRoute&&req.method==='POST'){try{const l=listings.get(offerRoute[1]),b=await body(req);return json(res,201,{offer:makeOffer(c,l,Math.round(Number(b.amount))),preview:true})}catch(e){return json(res,e.status||400,{error:e.message})}}
const offerRespond=url.pathname.match(/^\/api\/offers\/([^/]+)\/respond$/);if(offerRespond&&req.method==='POST'){try{const o=offers.get(offerRespond[1]),l=o?listings.get(o.listingId):null,b=await body(req);return json(res,200,respondOffer(c,o,l,String(b.action||'').toUpperCase(),b.amount))}catch(e){return json(res,e.status||400,{error:e.message})}}
const cancel=url.pathname.match(/^\/api\/orders\/([^/]+)\/cancel$/);if(cancel&&req.method==='POST'){const o=orders.get(cancel[1]);if(!o||o.buyerClientId!==c.id)return json(res,404,{error:'Order not found'});if(o.status!=='AWAITING_PAYMENT_CONNECTOR')return json(res,409,{error:'Order cannot be cancelled'});o.status='CANCELLED';const l=listings.get(o.listingId);if(l&&l.status==='RESERVED')l.status='ACTIVE';return json(res,200,{order:o})}
const message=url.pathname.match(/^\/api\/listings\/([^/]+)\/message$/);if(message&&req.method==='POST'){const l=listings.get(message[1]);if(!l)return json(res,404,{error:'Listing not found'});const b=await body(req),text=String(b.message||'').trim();if(text.length<4)return json(res,400,{error:'Message is too short'});const m={id:`msg-${crypto.randomUUID().slice(0,12)}`,listingId:l.id,lotId:l.lotId,sellerId:l.sellerId,buyerClientId:c.id,text:text.slice(0,1200),createdAt:nowIso(),status:'OPEN'};messages.set(m.id,m);return json(res,201,{message:m,preview:true})}
if(url.pathname==='/api/seller/listings'&&req.method==='POST'){try{const b=await body(req);const out=createSellerListing(c,b);return json(res,201,{...out,preview:true})}catch(e){return json(res,e.status||400,{error:e.message})}}
const submit=url.pathname.match(/^\/api\/seller\/listings\/([^/]+)\/submit$/);if(submit&&req.method==='POST'){const l=listings.get(submit[1]);if(!l||!c.sellerId||l.sellerId!==c.sellerId)return json(res,404,{error:'Listing not found'});if(l.status!=='DRAFT_REVIEW')return json(res,409,{error:'Only draft listings can be submitted'});l.status='PENDING_REVIEW';l.submittedAt=nowIso();return json(res,200,{listing:l,preview:true})}
if(url.pathname==='/api/private-sale/enquiry'&&req.method==='POST'){const b=await body(req);return json(res,201,{captured:true,preview:true,reference:`ENQ-${Date.now().toString(36).toUpperCase()}`,lotId:b.lotId||null})}
if(url.pathname==='/api/consignments'&&req.method==='POST'){const b=await body(req);if(!b.email||!b.category)return json(res,400,{error:'Email and category are required'});return json(res,201,{captured:true,preview:true,reference:`CON-${Date.now().toString(36).toUpperCase()}`})}
return json(res,404,{error:'Not found'});
}catch(e){return json(res,e.status||500,{error:e.message||'Unexpected server error'})}}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8'};
async function serve(req,res,url){let p=url.pathname==='/'?'/index.html':url.pathname;if(p.includes('..'))return json(res,400,{error:'Invalid path'});try{const d=await readFile(join(PUBLIC,p));res.writeHead(200,{'Content-Type':mime[extname(p)]||'application/octet-stream','Cache-Control':p==='/index.html'?'no-store':'public, max-age=300','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin'});res.end(d)}catch{const d=await readFile(join(PUBLIC,'index.html'));res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'});res.end(d)}}
http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);return url.pathname.startsWith('/api/')?await api(req,res,url):await serve(req,res,url)}catch(e){console.error(e);json(res,500,{error:'Unexpected server error'})}}).listen(PORT,'0.0.0.0',()=>console.log(`ANTIQUA 0.7 preview listening on ${PORT}`));
