import assert from 'node:assert/strict';import crypto from 'node:crypto';import {spawn} from 'node:child_process';import {readFile} from 'node:fs/promises';
const strongPassword=`Aa!${crypto.randomBytes(12).toString('hex')}9`,port=12109,base=`http://127.0.0.1:${port}`,child=spawn(process.execPath,['server-v09.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),PREVIEW_MODE:'true'},stdio:['ignore','pipe','pipe']});const sleep=ms=>new Promise(r=>setTimeout(r,ms));
class Browser{constructor(){this.c=new Map()}cookie(){return[...this.c].map(([k,v])=>`${k}=${v}`).join('; ')}async req(path,o={}){const m=(o.method||'GET').toUpperCase(),h={...(o.headers||{})};if(this.c.size)h.cookie=this.cookie();if(!['GET','HEAD'].includes(m)&&this.c.get('antiqua_csrf'))h['x-csrf-token']=this.c.get('antiqua_csrf');if(o.body&&!h['content-type'])h['content-type']='application/json';const r=await fetch(base+path,{...o,headers:h});for(const raw of r.headers.getSetCookie?.()||[]){const [p]=raw.split(';'),i=p.indexOf('='),k=p.slice(0,i),v=decodeURIComponent(p.slice(i+1));if(v)this.c.set(k,v);else this.c.delete(k)}return r}}
const jd=async r=>[r,await r.json()];
try{
 let ready=false;for(let i=0;i<50;i++){try{if((await fetch(base+'/api/health')).ok){ready=true;break}}catch{}await sleep(100)}assert.equal(ready,true);
 let r,d;[r,d]=await jd(await fetch(base+'/api/health'));assert.equal(d.version,'0.9.0');assert.equal(d.persistence.kind,'MEMORY_FALLBACK');assert.equal(d.objectStorage.configured,false);assert.equal(d.auth.passwordHash,'scrypt');assert.equal(d.auth.twoFactor,'TOTP');
 [r,d]=await jd(await fetch(base+'/api/catalog'));assert.ok(d.lots.length>=3);assert.ok(d.listings.length>=2);[r,d]=await jd(await fetch(base+'/api/lots/lot-107/passport'));assert.equal(d.lot.objectId,'AQ-107-2026');assert.ok(Array.isArray(d.riskFlags));
 const buyer=new Browser();[r,d]=await jd(await buyer.req('/api/auth/demo-login',{method:'POST',body:JSON.stringify({persona:'BUYER'})}));assert.ok(d.account.roles.includes('BUYER'));assert.ok(buyer.c.get('antiqua_session'));assert.ok(buyer.c.get('antiqua_csrf'));assert.equal('passwordHash' in d.account,false);[r,d]=await jd(await buyer.req('/api/client-state'));assert.equal(d.verification.status,'VERIFIED');
 const bad=new Browser();await bad.req('/api/auth/demo-login',{method:'POST',body:JSON.stringify({persona:'BUYER'})});bad.c.delete('antiqua_csrf');[r,d]=await jd(await bad.req('/api/lots/lot-107/save',{method:'POST',body:JSON.stringify({enabled:true})}));assert.equal(r.status,403);assert.equal(d.code,'CSRF_FAILED');
 await buyer.req(`/api/sales/sale-collector-2026-09/register`,{method:'POST',body:JSON.stringify({acceptTerms:true})});const cat=await(await buyer.req('/api/catalog')).json(),auc=cat.auctions[0],bidKey='bid-once';[r,d]=await jd(await buyer.req(`/api/auctions/${auc.id}/bid`,{method:'POST',headers:{'idempotency-key':bidKey},body:JSON.stringify({maxAmount:auc.currentBid+auc.increment*2})}));assert.equal(r.status,201);const count=d.auction.bidCount;[r,d]=await jd(await buyer.req(`/api/auctions/${auc.id}/bid`,{method:'POST',headers:{'idempotency-key':bidKey},body:JSON.stringify({maxAmount:auc.currentBid+auc.increment*2})}));assert.equal(r.status,200);assert.equal(d.idempotent,true);assert.equal(d.auction.bidCount,count);
 const seller=new Browser();await seller.req('/api/auth/demo-login',{method:'POST',body:JSON.stringify({persona:'SELLER'})});[r,d]=await jd(await buyer.req('/api/listings/lst-110/offers',{method:'POST',body:JSON.stringify({amount:4800})}));const offer=d.offer;[r,d]=await jd(await seller.req(`/api/offers/${offer.id}/respond`,{method:'POST',body:JSON.stringify({action:'COUNTER',amount:5200})}));assert.equal(d.offer.status,'COUNTERED_BY_SELLER');[r,d]=await jd(await buyer.req(`/api/offers/${offer.id}/respond`,{method:'POST',body:JSON.stringify({action:'ACCEPT'})}));assert.equal(d.order.status,'AWAITING_PAYMENT_CONNECTOR');
 const user=new Browser();[r,d]=await jd(await user.req('/api/auth/register',{method:'POST',body:JSON.stringify({email:'collector@antiqua.test',displayName:'Collector',password:strongPassword,accountType:'BUYER'})}));assert.equal(r.status,201);assert.equal('passwordHash' in d.account,false);[r,d]=await jd(await user.req('/api/auth/2fa/setup',{method:'POST',body:'{}'}));const code=d.currentPreviewCode;assert.ok(code);[r,d]=await jd(await user.req('/api/auth/2fa/confirm',{method:'POST',body:JSON.stringify({code})}));assert.equal(d.enabled,true);const recovery=d.backupCodes[0],rl=new Browser();[r,d]=await jd(await rl.req('/api/auth/login',{method:'POST',body:JSON.stringify({email:'collector@antiqua.test',password:strongPassword,totp:recovery})}));assert.equal(r.status,200);const rl2=new Browser();[r,d]=await jd(await rl2.req('/api/auth/login',{method:'POST',body:JSON.stringify({email:'collector@antiqua.test',password:strongPassword,totp:recovery})}));assert.equal(r.status,401);assert.equal(d.code,'INVALID_TWO_FACTOR');
 [r,d]=await jd(await seller.req('/api/media/upload-intent',{method:'POST',body:JSON.stringify({draftId:'draft-1',contentType:'image/jpeg',bytes:1000})}));assert.equal(r.status,503);assert.equal(d.code,'STORAGE_NOT_CONFIGURED');
 const img='https://images.metmuseum.org/CRDImages/es/web-large/DP247929.jpg';[r,d]=await jd(await seller.req('/api/seller/drafts/draft-1',{method:'PATCH',body:JSON.stringify({media:[{url:img},{url:img+'?detail=1'},{url:img+'?condition=1'}]})}));assert.equal(d.draft.checklist.ready,true);[r,d]=await jd(await seller.req('/api/seller/drafts/draft-1/submit',{method:'POST',body:'{}'}));assert.equal(d.draft.status,'CATALOGUE_REVIEW');
 const op=new Browser();[r,d]=await jd(await op.req('/api/auth/demo-login',{method:'POST',body:JSON.stringify({persona:'OPERATOR'})}));assert.ok(d.account.roles.includes('ADMIN'));[r,d]=await jd(await op.req('/api/operator/queue'));assert.ok(d.drafts.some(x=>x.id==='draft-1'));assert.ok(d.verifications.length>=3);[r,d]=await jd(await op.req('/api/operator/drafts/draft-1/approve',{method:'POST',body:'{}'}));assert.equal(d.review.catalogueStatus,'APPROVED');[r,d]=await jd(await op.req('/api/operator/drafts/draft-1/trust',{method:'POST',body:JSON.stringify({decision:'CLEARED',note:'Reviewed'})}));assert.equal(d.review.trustStatus,'CLEARED');const before=(await(await op.req('/api/catalog')).json()).lots.length;[r,d]=await jd(await op.req('/api/operator/drafts/draft-1/publish',{method:'POST',body:'{}'}));assert.equal(r.status,200);const after=(await(await op.req('/api/catalog')).json()).lots.length;assert.equal(after,before+1);[r,d]=await jd(await op.req('/api/operator/audit'));assert.ok(d.entries.some(x=>String(x.action).includes('PUBLISH')));
 const sql=await readFile(new URL('../migrations/001_v09_foundation.sql',import.meta.url),'utf8');for(const table of ['accounts','sessions','twofa_backup_codes','verification_cases','objects','provenance_entries','media_assets','auction_bids','orders','notifications','catalogue_reviews','audit_log'])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));
 const home=await fetch(base);assert.equal(home.status,200);assert.match(await home.text(),/Foundation 0\.9/);assert.equal((await fetch(base+'/app-v09.js')).status,200);console.log('ANTIQUA 0.9 smoke: 24/24 passed');
}finally{child.kill('SIGTERM')}
