import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {spawn} from 'node:child_process';
const port=11997,base=`http://127.0.0.1:${port}`;
const child=spawn(process.execPath,['server-v13.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),PREVIEW_MODE:'true',APP_SECRET:crypto.randomBytes(32).toString('hex'),NODE_ENV:'test'},stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
class Client{constructor(){this.cookies=new Map()}header(){return[...this.cookies].map(([k,v])=>`${k}=${v}`).join('; ')}async call(path,opts={}){const headers={'content-type':'application/json',...(opts.headers||{})};if(this.cookies.size)headers.cookie=this.header();if(!['GET','HEAD'].includes((opts.method||'GET').toUpperCase())&&this.cookies.get('antiqua_csrf'))headers['x-csrf-token']=decodeURIComponent(this.cookies.get('antiqua_csrf'));const r=await fetch(base+path,{...opts,headers});for(const s of r.headers.getSetCookie?.()||[]){const [kv]=s.split(';'),i=kv.indexOf('=');if(i>0)this.cookies.set(kv.slice(0,i),kv.slice(i+1))}let body;try{body=await r.json()}catch{body=null}return{r,body}}}
try{
 let ready=false;for(let i=0;i<100;i++){try{if((await fetch(base+'/api/health')).ok){ready=true;break}}catch{}await sleep(100)}assert.equal(ready,true);
 let r=await fetch(base+'/api/health'),h=await r.json();assert.equal(h.version,'0.13.0');assert.equal(h.uiVersion,'0.13.0');for(const k of ['nativeBilingualData','advancedFacets','compareObjects','productionAccount','productionDossier','fullscreenGallery','pinchZoom','dealerStorefront','collectionBuilder','exhibitionBuilder','ensembleMap'])assert.equal(h.interaction[k],true,k);assert.equal(h.auctionIntegrity.idempotencyRequired,true);assert.equal(h.collectionGraph.iiif,true);assert.equal(h.payments.ledgerSchema,true);
 const cat=await(await fetch(base+'/api/catalog')).json();assert.equal(cat.catalogueVersion,'0.13');assert.ok(cat.lots.length>=12);assert.ok(cat.listings.length>=6);assert.ok(cat.auctions.length>=6);for(const k of ['categories','eras','countries','materials','techniques','conditions','locations','purchaseMethods','sellers','price'])assert.ok(cat.facets[k],k);assert.ok(cat.facets.purchaseMethods.some(x=>x.value==='AUCTION'));assert.ok(cat.facets.purchaseMethods.some(x=>x.value==='MAKE_OFFER'));assert.ok(cat.facets.price.max>cat.facets.price.min);
 const l107=cat.lots.find(x=>x.id==='lot-107'),l109=cat.lots.find(x=>x.id==='lot-109');assert.ok(l107.technique.en&&l107.technique.ru);assert.ok(l107.locationLabel.en&&l107.locationLabel.ru);assert.ok(l107.purchaseMethods.includes('BUY_NOW'));assert.equal(l109.restoration.ru,'Отмечена историческая реставрация; детали ожидаются');const noRest=cat.lots.find(x=>String(x.restoration.en).startsWith('No restoration asserted'));assert.equal(noRest.restoration.ru,'В демонстрационной записи реставрация не заявлена');
 r=await fetch(base+'/api/lots/lot-107/passport');let p=await r.json();assert.equal(r.status,200);assert.equal(p.dossier.permanentPassport,true);assert.ok(p.commercial.listing);assert.equal(p.disclaimer.ru,'Каталожное одобрение не является гарантией подлинности.');
 r=await fetch(base+'/api/sellers/dealer-vermeer');let dealer=await r.json();assert.equal(r.status,200);assert.ok(dealer.inventory.length>=2);assert.ok(dealer.inventory[0].lot.technique.en);
 r=await fetch(base+'/api/collections');let col=await r.json();assert.ok(col.collections.length>=1);r=await fetch(base+'/api/ensembles');let ens=await r.json();assert.ok(ens.ensembles[0].completeness.total>=ens.ensembles[0].completeness.known);r=await fetch(base+'/api/exhibitions');let exs=await r.json();assert.ok(exs.exhibitions.length>=1);r=await fetch(base+'/api/lots/lot-101/iiif/manifest');assert.equal((await r.json()).type,'Manifest');r=await fetch(base+'/api/lots/lot-101/linked-art');assert.equal((await r.json()).type,'HumanMadeObject');
 const homeR=await fetch(base),home=await homeR.text();assert.equal(homeR.status,200);assert.match(home,/styles-v13\.css/);assert.match(home,/app-v13\.js/);assert.doesNotMatch(home,/app-v10\.js/);assert.doesNotMatch(home,/ux-v11\.js/);assert.doesNotMatch(home,/commerce-v11\.js/);assert.doesNotMatch(home,/experience-v12\.js/);assert.match(home,/data-lang="ru"/);assert.match(home,/data-lang="en"/);
 for(const [file,mime] of [['styles-v13.css','text/css'],['app-v13.js','javascript']]){const x=await fetch(`${base}/${file}`);assert.equal(x.status,200);assert.match(x.headers.get('content-type')||'',new RegExp(mime));const text=await x.text();assert.ok(text.length>4000);if(file.endsWith('.js')){for(const token of ['filteredEntries','compareView','passport(id)','native-dossier','data-filter','pinchZoom','setup2fa'])assert.match(text,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),token);assert.doesNotMatch(text,/TreeWalker/);assert.doesNotMatch(text,/exactRu/)}else{for(const token of ['facet-panel','compare-grid','native-dossier','catalog-layout'])assert.match(text,new RegExp(token))}}
 const buyer=new Client();let x=await buyer.call('/api/auth/demo-login',{method:'POST',body:JSON.stringify({persona:'BUYER'})});assert.equal(x.r.status,200);x=await buyer.call('/api/client-state');assert.equal(x.r.status,200);x=await buyer.call('/api/lots/lot-107/save',{method:'POST',body:JSON.stringify({enabled:true})});assert.equal(x.r.status,200);x=await buyer.call('/api/client-state');assert.ok(x.body.savedLots.includes('lot-107'));
 const auction=(await buyer.call('/api/catalog')).body.auctions[0],sale=cat.sale;x=await buyer.call(`/api/sales/${sale.id}/register`,{method:'POST',body:JSON.stringify({acceptTerms:true,termsVersion:'ci-v13'})});assert.equal(x.r.status,200);const idem='v13-'+crypto.randomUUID(),max=auction.currentBid+auction.increment*8;x=await buyer.call(`/api/auctions/${auction.id}/bid`,{method:'POST',headers:{'idempotency-key':idem},body:JSON.stringify({maxAmount:max})});assert.equal(x.r.status,201);const count=x.body.auction.bidCount;x=await buyer.call(`/api/auctions/${auction.id}/bid`,{method:'POST',headers:{'idempotency-key':idem},body:JSON.stringify({maxAmount:max})});assert.equal(x.r.status,200);assert.equal(x.body.idempotent,true);assert.equal(x.body.auction.bidCount,count);
 const buyer2=new Client(),password=`Aa1!${crypto.randomBytes(18).toString('base64url')}`;x=await buyer2.call('/api/auth/register',{method:'POST',body:JSON.stringify({email:`v13-${crypto.randomUUID()}@example.test`,displayName:'V13 Buyer',password,accountType:'BUYER'})});assert.equal(x.r.status,201);x=await buyer2.call(`/api/sales/${sale.id}/register`,{method:'POST',body:JSON.stringify({acceptTerms:true,termsVersion:'ci-v13'})});assert.equal(x.r.status,200);const fresh=(await(await fetch(base+'/api/catalog')).json()).auctions.find(a=>a.id===auction.id);const [a1,a2]=await Promise.all([buyer.call(`/api/auctions/${auction.id}/bid`,{method:'POST',headers:{'idempotency-key':'a-'+crypto.randomUUID()},body:JSON.stringify({maxAmount:fresh.currentBid+fresh.increment*20})}),buyer2.call(`/api/auctions/${auction.id}/bid`,{method:'POST',headers:{'idempotency-key':'b-'+crypto.randomUUID()},body:JSON.stringify({maxAmount:fresh.currentBid+fresh.increment*24})})]);assert.equal(a1.r.status,201);assert.equal(a2.r.status,201);const finalA=(await(await fetch(base+'/api/catalog')).json()).auctions.find(a=>a.id===auction.id);assert.equal(finalA.bidCount,count+2);assert.ok(finalA.currentBid>fresh.currentBid);
 const exId=exs.exhibitions[0].id;let publicEx=await(await fetch(base+`/api/exhibitions/${exId}`)).json();assert.equal(publicEx.editable,false);const owned=await buyer.call(`/api/exhibitions/${exId}`);assert.equal(owned.r.status,200);assert.equal(owned.body.editable,true);const first=owned.body.exhibition.sections[0],before=first.items.map(i=>i.objectId?`o:${i.objectId}`:`e:${i.ensembleId}`);const sections=owned.body.exhibition.sections.map((s,i)=>({sectionId:s.id,items:(i===0?[...s.items].reverse():s.items).map(v=>v.objectId?{objectId:v.objectId}:{ensembleId:v.ensembleId})}));x=await buyer.call(`/api/exhibitions/${exId}/layout`,{method:'PATCH',body:JSON.stringify({sections})});assert.equal(x.r.status,200);const after=x.body.exhibition.sections[0].items.map(i=>i.objectId?`o:${i.objectId}`:`e:${i.ensembleId}`);assert.deepEqual(after,[...before].reverse());
 console.log('ANTIQUA 0.13 smoke: native bilingual app + facets + compare + auction integrity + collection graph passed');
}finally{child.kill('SIGTERM')}
