import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {spawn} from 'node:child_process';
const port=11998,base=`http://127.0.0.1:${port}`;
const child=spawn(process.execPath,['server-v14.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),PREVIEW_MODE:'true',APP_SECRET:crypto.randomBytes(32).toString('hex'),NODE_ENV:'test'},stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
class Client{constructor(){this.cookies=new Map()}header(){return[...this.cookies].map(([k,v])=>`${k}=${v}`).join('; ')}async call(path,opts={}){const headers={'content-type':'application/json',...(opts.headers||{})};if(this.cookies.size)headers.cookie=this.header();if(!['GET','HEAD'].includes((opts.method||'GET').toUpperCase())&&this.cookies.get('antiqua_csrf'))headers['x-csrf-token']=decodeURIComponent(this.cookies.get('antiqua_csrf'));const r=await fetch(base+path,{...opts,headers});for(const s of r.headers.getSetCookie?.()||[]){const [kv]=s.split(';'),i=kv.indexOf('=');if(i>0)this.cookies.set(kv.slice(0,i),kv.slice(i+1))}let body;try{body=await r.json()}catch{body=null}return{r,body}}}
const login=async persona=>{const c=new Client(),x=await c.call('/api/auth/demo-login',{method:'POST',body:JSON.stringify({persona})});assert.equal(x.r.status,200);return c};
try{
 let ready=false;for(let i=0;i<120;i++){try{if((await fetch(base+'/api/health')).ok){ready=true;break}}catch{}await sleep(100)}assert.equal(ready,true);
 let h=await(await fetch(base+'/api/health')).json();assert.equal(h.version,'0.14.0');assert.equal(h.uiVersion,'0.14.0');assert.equal(h.e2e.discovery.savedSearches,true);assert.equal(h.e2e.messaging.threads,true);assert.equal(h.e2e.collection.insurance,true);assert.equal(h.e2e.auctionSettlement.nonpayment,true);assert.equal(h.e2e.shipping.deliveryProof,true);assert.equal(h.e2e.disputes.evidence,true);assert.equal(h.e2e.providers.eventIdempotency,true);assert.equal(h.externalProviders.payment,'NOT_CONFIGURED');
 let raw=await fetch(base+'/api/providers/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({providerType:'PAYMENT',provider:'none',externalEventId:'x'})});assert.equal(raw.status,503);
 const buyer=await login('BUYER'),sellerClient=await login('SELLER'),operator=await login('OPERATOR');
 let x=await buyer.call('/api/discovery/subscriptions',{method:'POST',body:JSON.stringify({subscriptionType:'SAVED_SEARCH',label:'Bronze',criteria:{material:'bronze'}})});assert.equal(x.r.status,201);assert.ok(x.body.subscription.matchCount>=1);x=await buyer.call('/api/discovery/subscriptions');assert.equal(x.r.status,200);assert.ok(x.body.subscriptions.some(s=>s.matchCount>=1));
 x=await buyer.call('/api/conversations',{method:'POST',body:JSON.stringify({listingId:'lst-109',subject:'Walnut commode'})});assert.equal(x.r.status,201);const conversationId=x.body.conversation.id;const msgId='m-'+crypto.randomUUID();x=await buyer.call(`/api/conversations/${conversationId}/messages`,{method:'POST',body:JSON.stringify({body:'Please confirm the condition before purchase.',clientMessageId:msgId})});assert.equal(x.r.status,201);x=await buyer.call(`/api/conversations/${conversationId}/messages`,{method:'POST',body:JSON.stringify({body:'duplicate',clientMessageId:msgId})});assert.equal(x.r.status,200);assert.equal(x.body.idempotent,true);x=await sellerClient.call('/api/conversations');assert.ok(x.body.conversations.some(c=>c.id===conversationId&&c.unreadCount>=1));x=await sellerClient.call(`/api/conversations/${conversationId}/messages`,{method:'POST',body:JSON.stringify({body:'Condition report is available.',clientMessageId:'s-'+crypto.randomUUID()})});assert.equal(x.r.status,201);x=await buyer.call(`/api/conversations/${conversationId}`);assert.equal(x.body.conversation.messages.length,2);await buyer.call(`/api/conversations/${conversationId}/read`,{method:'POST',body:'{}'});
 x=await buyer.call('/api/collection-records/lot-109',{method:'PUT',body:JSON.stringify({status:'OWNED',acquisition:{source:'PRIVATE'},appraisal:{value:8200,currency:'EUR'},storage:{city:'Amsterdam'},privateNotes:'Study collection'})});assert.equal(x.r.status,200);x=await buyer.call('/api/collection-records/lot-109/movements',{method:'POST',body:JSON.stringify({movementType:'MOVED',fromLocation:{city:'Amsterdam'},toLocation:{city:'Rotterdam'},note:'Temporary storage'})});assert.equal(x.r.status,201);x=await buyer.call('/api/collection-records/lot-109/insurance',{method:'POST',body:JSON.stringify({provider:'Preview Fine Art Insurance',policyNumberMasked:'***1042',insuredValueMinor:900000,currency:'EUR',coverage:{transit:true}})});assert.equal(x.r.status,201);x=await buyer.call('/api/collection-records');const rec=x.body.records.find(r=>r.objectId==='lot-109');assert.ok(rec.movements.length>=2);assert.equal(rec.policies.length,1);
 x=await buyer.call('/api/listings/lst-109/buy',{method:'POST',body:'{}'});assert.equal(x.r.status,201);const orderId=x.body.order.id;x=await buyer.call(`/api/orders/${orderId}/payment-preview`,{method:'POST',body:'{}'});assert.equal(x.r.status,201);assert.equal(x.body.order.paymentStatus,'PAID');assert.equal(x.body.shipment.status,'QUOTE_REQUIRED');const shipmentId=x.body.shipment.id,payoutId=x.body.payout.id;
 x=await buyer.call(`/api/shipments/${shipmentId}/quote`,{method:'POST',body:JSON.stringify({origin:'Amsterdam',destination:'Utrecht'})});assert.equal(x.body.shipment.status,'QUOTED');for(const status of ['BOOKED','PACKING','IN_TRANSIT','DELIVERED']){x=await sellerClient.call(`/api/shipments/${shipmentId}/transition`,{method:'POST',body:JSON.stringify({status,trackingReference:'TRK-001',packageSpec:{photos:4,sealed:true},deliveryProof:status==='DELIVERED'?{signedBy:'Buyer'}:{}})});assert.equal(x.r.status,200);assert.equal(x.body.shipment.status,status)}
 x=await buyer.call('/api/disputes',{method:'POST',body:JSON.stringify({orderId,shipmentId,category:'MISMATCH',summary:'Condition detail needs clarification',requestedResolution:'Review evidence'})});assert.equal(x.r.status,201);const disputeId=x.body.dispute.id;x=await buyer.call(`/api/disputes/${disputeId}/evidence`,{method:'POST',body:JSON.stringify({evidenceType:'PHOTO_NOTE',note:'Detail photo supplied',mediaIds:[]})});assert.equal(x.r.status,201);x=await buyer.call(`/api/shipments/${shipmentId}/confirm-receipt`,{method:'POST',body:'{}'});assert.equal(x.r.status,409);x=await operator.call(`/api/disputes/${disputeId}/decision`,{method:'POST',body:JSON.stringify({status:'RESOLVED_SELLER',reason:'Evidence reviewed; item accepted'})});assert.equal(x.r.status,200);x=await buyer.call(`/api/shipments/${shipmentId}/confirm-receipt`,{method:'POST',body:'{}'});assert.equal(x.r.status,200);assert.equal(x.body.confirmed,true);assert.equal(x.body.record.status,'OWNED');assert.equal(x.body.payout.status,'READY');
 x=await operator.call(`/api/payouts/${payoutId}/provider-state`,{method:'POST',body:JSON.stringify({status:'SUBMITTED',provider:'PREVIEW_PSP',providerReference:'po-1'})});assert.equal(x.body.payout.status,'SUBMITTED');x=await operator.call(`/api/payouts/${payoutId}/provider-state`,{method:'POST',body:JSON.stringify({status:'PAID',provider:'PREVIEW_PSP',providerReference:'po-1'})});assert.equal(x.body.payout.status,'PAID');
 const buyer2=new Client(),pw=['A','a','1','!'].join('')+crypto.randomBytes(16).toString('hex');x=await buyer2.call('/api/auth/register',{method:'POST',body:JSON.stringify({email:`v14-${crypto.randomUUID()}@example.test`,displayName:'V14 Buyer',password:pw,accountType:'BUYER'})});assert.equal(x.r.status,201);
 const cat=await(await fetch(base+'/api/catalog')).json(),auction=cat.auctions[0];for(const c of [buyer,buyer2]){x=await c.call(`/api/sales/${cat.sale.id}/register`,{method:'POST',body:JSON.stringify({acceptTerms:true,termsVersion:'ci-v14'})});assert.equal(x.r.status,200)}
 const fresh=await(await fetch(base+'/api/catalog')).json(),a0=fresh.auctions.find(a=>a.id===auction.id);x=await buyer.call(`/api/auctions/${a0.id}/bid`,{method:'POST',headers:{'idempotency-key':'v14a-'+crypto.randomUUID()},body:JSON.stringify({maxAmount:a0.currentBid+a0.increment*20})});assert.equal(x.r.status,201);x=await buyer2.call(`/api/auctions/${a0.id}/bid`,{method:'POST',headers:{'idempotency-key':'v14b-'+crypto.randomUUID()},body:JSON.stringify({maxAmount:a0.currentBid+a0.increment*24})});assert.equal(x.r.status,201);
 x=await operator.call(`/api/operator/auctions/${a0.id}/close-preview`,{method:'POST',body:'{}'});assert.equal(x.r.status,201);const settlement=x.body.settlement;assert.equal(settlement.status,'PAYMENT_DUE');const winner=settlement.buyerAccountId===(await buyer.call('/api/client-state')).body.id?buyer:buyer2;x=await winner.call(`/api/settlements/${settlement.id}/payment-preview`,{method:'POST',body:'{}'});assert.equal(x.r.status,201);assert.equal(x.body.settlement.status,'PAID');assert.equal(x.body.shipment.status,'QUOTE_REQUIRED');
 const a1=(await(await fetch(base+'/api/catalog')).json()).auctions.find(a=>a.id!==a0.id);for(const c of [buyer,buyer2]){x=await c.call(`/api/auctions/${a1.id}/bid`,{method:'POST',headers:{'idempotency-key':'v14-'+crypto.randomUUID()},body:JSON.stringify({maxAmount:a1.currentBid+a1.increment*30})});assert.equal(x.r.status,201)}x=await operator.call(`/api/operator/auctions/${a1.id}/close-preview`,{method:'POST',body:'{}'});assert.equal(x.r.status,201);const nonpay=x.body.settlement;x=await operator.call(`/api/settlements/${nonpay.id}/nonpayment`,{method:'POST',body:JSON.stringify({reason:'deadline'})});assert.equal(x.body.settlement.status,'NONPAYMENT');x=await operator.call(`/api/settlements/${nonpay.id}/reoffer`,{method:'POST',body:'{}'});assert.equal(x.body.settlement.status,'REOFFERED');assert.equal(x.body.settlement.buyerAccountId,nonpay.buyerAccountId);
 console.log('ANTIQUA 0.14 smoke: discovery + messaging + collection/insurance + commerce + shipping/disputes + auction settlement + payout lifecycle passed');
}finally{child.kill('SIGTERM')}
